---
title: "Map"
date: "2022-12-02"
output: html_document
---


```{r}
library(tidyverse)
library(plotly)
library(tigris)
library(tidycensus)

knitr::opts_chunk$set(
	echo = FALSE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



```{r}
ny_counties <-
  counties(state = "36", cb = TRUE, resolution = "20m") %>% 
  janitor::clean_names()

ny_abortion = 
  read_csv(file = "data/master.csv") %>%
  janitor::clean_names() %>%
  transform(borough = gsub(pattern = "Brooklyn", replacement = "Kings", borough)) %>%
  transform(borough = gsub(pattern = "Manhattan", replacement = "New York", borough)) %>%
  transform(borough = gsub(pattern = "Staten Island", replacement = "Richmond", borough)) %>%
  transform(borough = gsub(pattern = "Essex/Hamilton", replacement = "Essex", borough)) %>%
  transform(borough = gsub(pattern = "St Lawrence", replacement = "St. Lawrence", borough)) %>% 
  rename(name = borough) %>% 
  mutate(total = round(total, digits = 0)) %>% 
  select(name, everything())

ny_total_geo = full_join(ny_counties, ny_abortion, by = "name")

test <- ggplot(data = ny_total_geo, aes(fill = total)) + 
  geom_sf() + 
  labs(title = "Total Abortion Ratios by New York State Counties",
       caption = "Data source: 2019 Table 22, New York State Department of Health",
       fill = "Abortion Ratio = 
       Number of Induced Abortions per 1,000 Live Births") + 
  theme_void()

fig <- ggplotly(test)

fig

test2 <- ggplot(data = ny_total_geo) +
  geom_sf(aes(fill = total, text = paste(name, total))) + 
  labs(title = "Total Abortion Ratios by New York State Counties",
       caption = "Data source: 2019 Table 22, New York State Department of Health",
       fill = "Abortion Ratio = 
       Number of Induced Abortions 
       per 1,000 Live Births")

test2 %>% 
  ggplotly(tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white"), hoveron = "fill")
```


## Incorporating year data


