<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Project Report</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Overview</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Exploratory Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ny_exploratory_analysis.html">New York State Analysis</a>
    </li>
    <li>
      <a href="nyc_exploratory_analysis.html">New York City Analysis</a>
    </li>
    <li>
      <a href="comparative.html">Comparative Analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Statistical Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="nys_statistical_analysis.html">NYS Statistical Analysis</a>
    </li>
    <li>
      <a href="nyc_statistical_analysis.html">NYC Statistical Analysis</a>
    </li>
    <li>
      <a href="comparative_statistical_analysis.html">Comparative Statistical Analysis</a>
    </li>
  </ul>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    About
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="team.html">Our Team</a>
    </li>
    <li>
      <a href="proposal.html">Project Proposal</a>
    </li>
  </ul>
</li>
<li>
  <a href="mailto:&lt;yc4017@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/ElaineYanxi-Chen/p8105-finalproject.github.io.git">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Project Report</h1>

</div>


<p> </p>
<div id="motivation" class="section level1">
<h1>Motivation</h1>
<hr />
<p>In 2019, many states raced to enact an unprecedented wave of bans on
abortions that have severely restricted Women’s reproductive rights.
These restrictions have culminated to the recent Supreme Court
overturning of Roe v. Wade, a landmark supreme court case granting a
Women’s right to an abortion.</p>
<p><img src="images/2019_abortion.jpg" style = "width:70%"></p>
<p>Source: <a
href="https://www.guttmacher.org/article/2019/12/state-policy-trends-2019-wave-abortion-bans-some-states-are-fighting-back">Guttmacher
Institute</a></p>
<p>Our year of interest is 2019, which is the most recent dataset
provided by New York State and final year before the COVID-19 pandemic.
We will be focusing on the number of induced abortions per 1,000 live
births in New York City and New York State and compare the differences
across boroughs (for New York City), counties (for New York State), and
between New York City and New York State. Variables we are considering
are age, race/ethnicity, and financial plans (a.k.a. insurance plans).
Those that are likely to be most impacted by this decision are
individuals that belong to under-served and marginalized communities. We
wanted to better understand disparities in abortion access.</p>
<p> </p>
</div>
<div id="initial-questions" class="section level1">
<h1>Initial questions</h1>
<hr />
<p>Originally, we wanted to conduct a comparative analysis of abortion
rates in New York and Mississippi from 2017-2020 to answer the following
questions:</p>
<ul>
<li>Have abortion rates changed over time (2017 to 2020) in New York and
Mississippi?</li>
<li>What does the distribution of abortion rates between counties within
New York and Mississippi look like?</li>
<li>Are abortion rates different in New York compared to Mississippi
while accounting for age, race/ethnicity, method, and insurance
plan?</li>
</ul>
</div>
<div id="final-research-questions" class="section level1">
<h1>Final Research Questions</h1>
<hr />
<p>We were unable to find a comprehensive dataset that included
individual level data needed to answer these questions. Therefore, we
decided to focus on conducting an analysis of abortion rates in New York
City and New York State in 2019. Our research questions changed to the
following:</p>
<ul>
<li>What does the distribution of rates of abortion between boroughs
within New York City look like in 2019?
<ul>
<li>Are abortion rates different among boroughs in New York City while
accounting for age, race/ethnicity, and finance plans in 2019?</li>
</ul></li>
<li>How do abortion rates differ between New York City and New York
State in 2019?</li>
<li>How do abortion rates differ within regions/counties of New York
State in 2019?
<ul>
<li>Are abortion rates different among regions/counties of New York
State while accounting for age, race/ethnicity, and finance plans?</li>
</ul></li>
</ul>
<p> </p>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<hr />
<div id="source" class="section level2">
<h2>Source</h2>
<p>For this project, we will use data from <a
href="https://www.health.ny.gov/statistics/vital_statistics/">Vital
Statistics of New York State 2014-2019</a> which consists of group-level
data from New York City and New York State for age, race/ethnicity, and
finance plans, each being its own data set.</p>
<ul>
<li><p>The data were collected from the New York State Bureau of Vital
Records who maintains a registry of all births, marriages,
divorces/dissolutions of marriage, deaths, induced termination of
pregnancy/abortions, and fetal deaths that have occurred in New York
State.</p></li>
<li><p>The <a
href="https://www.health.ny.gov/health_care/medicaid/redesign/ehr/registry/nycdohmh.htm">New
York City Department of Health and Mental Hygiene</a> sends data on on
live births, deaths, fetal deaths, induced terminations of
pregnancy/abortions (abortion), marriages, and divorces/dissolutions of
marriage recorded in New York City to the New York State Department of
Health.</p></li>
<li><p>The New York State Department of Health receives data on live
births and deaths recorded outside of New York State to residents of New
York State from other states and Canada.</p></li>
<li><p>The geographical units are categorized as follows:</p>
<ul>
<li><p>New York City includes five counties: Bronx, Kings (Brooklyn),
New York (Manhattan), Queens, and Richmond (Staten Island). Each county
corresponds to a borough.</p></li>
<li><p>New York State encompasses 10 regions: Central New York, Eastern
Adirondacks, Western Adirondacks, Saratoga, Finger Lakes, Western New
York, Hudson Valley, Westchester/Rockland, Long Island, and New York
City.</p></li>
<li><p>New York State encompasses 62 counties, including five from New
York City.</p></li>
</ul></li>
</ul>
<p>From the Vital Statistics of New York State 2019, we will use data
from the <em>Induced Abortions</em> and <em>Live Births</em> section in
order to find information on finance plans.</p>
</div>
<div id="data-scraping-and-cleaning" class="section level2">
<h2>Data Scraping and Cleaning</h2>
<p>We first imported the data sets representing abortion rates from the
Vital Statistics of New York State 2019 webpage. We cleaned and merged
the data appropriately to create a final master spreadsheet, which we
will be pulling from for each of our analyses.</p>
<p>For the finance plans data set, we imported the number of induced
abortion and number of live births in order to calculate the abortion
rates manually. The equation we used is as follows:</p>
<p><span class="math display">\[Abortion\ Rate\ per\ 1000\ Live\ Births\
= \frac{Count}{Number\ of\ Live\ Births} \times 1000\]</span></p>
<p>We renamed variable names for the different counties in New York City
to the name of the respective boroughs. Final variable names in our
dataset for New York City include:</p>
<ul>
<li><code>Manhattan</code></li>
<li><code>Bronx</code></li>
<li><code>Brooklyn</code></li>
<li><code>Queens</code></li>
<li><code>Staten Island</code></li>
</ul>
<p>From the same dataset, we included <code>New York State</code> total,
<code>New York City</code> total and any county with released abortion
rate data. Therefore, the dataset includes the following variables: New
York State, New York City, Bronx, Brooklyn, Manhattan, Queens, Staten
Island, Albany, Allegany, Broome, Cattaraugus, Cayuga, Chautauqua,
Chemung, Chenango, Clinton, Columbia, Cortland, Delaware, Dutchess,
Erie, Essex/Hamilton, Franklin, Fulton, Greene, Herkimer, Jefferson,
Lewis, Livingston, Madison, Monroe, Montgomery, Nassau, Niagara, Oneida,
Onondaga, Ontario, Orange, Orleans, Oswego, Otsego, Putnam, Rensselaer,
Rockland, St Lawrence, Saratoga, Schenectady, Schoharie, Schuyler,
Seneca, Steuben, Suffolk, Sullivan, Tioga, Tompkins, Ulster, Warren,
Washington, Wayne, Westchesterto analyze data for New York state.</p>
<p>One note is that Essex County and Hamilton County data are combined
in the dataset provided by New York state. Therefore,
<code>Essex/Hamilton</code> is used as a combined variable, rather than
separate variables.</p>
<p>Counties were recoded into regions based on categories set by New
York State using <code>transform</code> or <code>case_when</code>. Some
counties had very few abortion numbers, which would not provide a
sufficient sample size when stratifying based on our covariates. As a
result, the categorizing of the regions will ensure a sufficient sample
size for some of the analyses.</p>
<p>The final regions included in the dataset for New York State
includes:</p>
<ul>
<li><code>Central New York</code></li>
<li><code>Eastern Adirondacks</code></li>
<li><code>Western Adirondacks</code></li>
<li><code>Saratoga</code></li>
<li><code>Finger Lakes</code></li>
<li><code>Western New York</code></li>
<li><code>Hudson Valley</code></li>
<li><code>Westchester/Rockland</code></li>
<li><code>Long Island</code></li>
<li><code>New York City</code></li>
</ul>
<p>The regions were created based on this <a
href="https://statejobs.ny.gov/assets/help/regionMapText.cfm">website</a></p>
<p>Specific data cleaning processes for the covariates are listed
below.</p>
<div id="age" class="section level4">
<h4>Age</h4>
<p>Age was categorized as follows:</p>
<ul>
<li><code>age_less_20</code></li>
<li><code>age_20_24</code></li>
<li><code>age_25_29</code></li>
<li><code>age_30_34</code></li>
<li><code>age_35_39</code></li>
<li><code>age_plus_40</code></li>
</ul>
</div>
<div id="raceethnicity" class="section level4">
<h4>Race/Ethnicity</h4>
<p>Race/Ethnicity was categorized as follows:</p>
<ul>
<li><code>Non-Hispanic White</code></li>
<li><code>Non-Hispanic Black</code></li>
<li><code>Non-Hispanic Others</code></li>
<li><code>Hispanic</code></li>
</ul>
<p>Ethnicity is distinguished from race and is based on the ethnicity of
the mother. Ethnicity distinguishes individuals of Spanish origin
regardless of race. Race was self-reported.</p>
</div>
<div id="financial-plan-status" class="section level4">
<h4>Financial Plan Status</h4>
<p>The final variable names include:</p>
<ul>
<li><code>Medicaid</code></li>
<li><code>Other_insurance</code></li>
<li><code>self_pay</code></li>
<li><code>not stated</code></li>
</ul>
<p>The technical notes in the dataset did not specify which plans were
included under the <code>other_insurance</code> category.</p>
<p>After individual datasets were tidied, they were merged into a final
dataset which was then saved and exported to our project repository.
These steps were necessary to ensure that the code was readable and
reproducible.</p>
</div>
<div id="final-dataset" class="section level3">
<h3>Final Dataset</h3>
<p>Here is our final, cleaned and tidied dataset:</p>
<div
style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:800px; ">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
Borough
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
Region
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Total
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
&lt;20
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
20-24
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
25-29
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
30-34
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
35-39
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
40+
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Non-Hipanic Total
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Non-Hispanic White
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Non-Hispanic Black
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Non-Hispanic Other
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Hispanic Total
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Hispanic White
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Hispanic Black
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Medicaid
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Self-Pay
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
Other Insurance
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
Not Stated
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
New York State
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:center;">
336.5
</td>
<td style="text-align:center;">
1012.9
</td>
<td style="text-align:center;">
588.8
</td>
<td style="text-align:center;">
378.4
</td>
<td style="text-align:center;">
214.6
</td>
<td style="text-align:center;">
203.4
</td>
<td style="text-align:center;">
269.1
</td>
<td style="text-align:center;">
334.1
</td>
<td style="text-align:center;">
142.9
</td>
<td style="text-align:center;">
758.5
</td>
<td style="text-align:center;">
202.1
</td>
<td style="text-align:center;">
344.4
</td>
<td style="text-align:center;">
189.0
</td>
<td style="text-align:center;">
534.6
</td>
<td style="text-align:center;">
325.7
</td>
<td style="text-align:center;">
3755.0
</td>
<td style="text-align:left;">
10322.6
</td>
<td style="text-align:left;">
3252.4
</td>
</tr>
<tr>
<td style="text-align:left;">
New York City
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:center;">
450.5
</td>
<td style="text-align:center;">
1491.4
</td>
<td style="text-align:center;">
792.2
</td>
<td style="text-align:center;">
526.8
</td>
<td style="text-align:center;">
302.8
</td>
<td style="text-align:center;">
264.2
</td>
<td style="text-align:center;">
323.0
</td>
<td style="text-align:center;">
459.4
</td>
<td style="text-align:center;">
165.6
</td>
<td style="text-align:center;">
851.7
</td>
<td style="text-align:center;">
243.2
</td>
<td style="text-align:center;">
428.1
</td>
<td style="text-align:center;">
167.7
</td>
<td style="text-align:center;">
570.6
</td>
<td style="text-align:center;">
401.7
</td>
<td style="text-align:center;">
8801.2
</td>
<td style="text-align:left;">
19924.4
</td>
<td style="text-align:left;">
1477.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Bronx
</td>
<td style="text-align:left;">
New York City
</td>
<td style="text-align:center;">
623.3
</td>
<td style="text-align:center;">
1291.9
</td>
<td style="text-align:center;">
860.8
</td>
<td style="text-align:center;">
605.0
</td>
<td style="text-align:center;">
497.1
</td>
<td style="text-align:center;">
443.1
</td>
<td style="text-align:center;">
447.8
</td>
<td style="text-align:center;">
786.6
</td>
<td style="text-align:center;">
369.8
</td>
<td style="text-align:center;">
734.3
</td>
<td style="text-align:center;">
419.3
</td>
<td style="text-align:center;">
500.2
</td>
<td style="text-align:center;">
172.2
</td>
<td style="text-align:center;">
684.6
</td>
<td style="text-align:center;">
488.5
</td>
<td style="text-align:center;">
6150.9
</td>
<td style="text-align:left;">
31915.1
</td>
<td style="text-align:left;">
1498.1
</td>
</tr>
<tr>
<td style="text-align:left;">
Brooklyn
</td>
<td style="text-align:left;">
New York City
</td>
<td style="text-align:center;">
351.7
</td>
<td style="text-align:center;">
1388.4
</td>
<td style="text-align:center;">
515.3
</td>
<td style="text-align:center;">
412.6
</td>
<td style="text-align:center;">
251.8
</td>
<td style="text-align:center;">
210.5
</td>
<td style="text-align:center;">
242.8
</td>
<td style="text-align:center;">
343.7
</td>
<td style="text-align:center;">
88.6
</td>
<td style="text-align:center;">
837.7
</td>
<td style="text-align:center;">
162.5
</td>
<td style="text-align:center;">
393.1
</td>
<td style="text-align:center;">
214.2
</td>
<td style="text-align:center;">
432.0
</td>
<td style="text-align:center;">
287.0
</td>
<td style="text-align:center;">
8644.4
</td>
<td style="text-align:left;">
19678.4
</td>
<td style="text-align:left;">
2058.8
</td>
</tr>
<tr>
<td style="text-align:left;">
Manhattan
</td>
<td style="text-align:left;">
New York City
</td>
<td style="text-align:center;">
537.5
</td>
<td style="text-align:center;">
1964.9
</td>
<td style="text-align:center;">
1768.6
</td>
<td style="text-align:center;">
988.1
</td>
<td style="text-align:center;">
312.2
</td>
<td style="text-align:center;">
256.5
</td>
<td style="text-align:center;">
312.0
</td>
<td style="text-align:center;">
542.9
</td>
<td style="text-align:center;">
320.8
</td>
<td style="text-align:center;">
1228.3
</td>
<td style="text-align:center;">
253.2
</td>
<td style="text-align:center;">
519.8
</td>
<td style="text-align:center;">
220.6
</td>
<td style="text-align:center;">
601.4
</td>
<td style="text-align:center;">
708.4
</td>
<td style="text-align:center;">
31285.7
</td>
<td style="text-align:left;">
62864.4
</td>
<td style="text-align:left;">
576.6
</td>
</tr>
<tr>
<td style="text-align:left;">
Queens
</td>
<td style="text-align:left;">
New York City
</td>
<td style="text-align:center;">
445.7
</td>
<td style="text-align:center;">
1780.1
</td>
<td style="text-align:center;">
915.6
</td>
<td style="text-align:center;">
476.5
</td>
<td style="text-align:center;">
282.9
</td>
<td style="text-align:center;">
275.7
</td>
<td style="text-align:center;">
396.4
</td>
<td style="text-align:center;">
494.2
</td>
<td style="text-align:center;">
155.0
</td>
<td style="text-align:center;">
895.1
</td>
<td style="text-align:center;">
273.1
</td>
<td style="text-align:center;">
329.4
</td>
<td style="text-align:center;">
80.4
</td>
<td style="text-align:center;">
287.4
</td>
<td style="text-align:center;">
408.6
</td>
<td style="text-align:center;">
6299.2
</td>
<td style="text-align:left;">
33991.0
</td>
<td style="text-align:left;">
3519.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Staten Island
</td>
<td style="text-align:left;">
New York City
</td>
<td style="text-align:center;">
275.6
</td>
<td style="text-align:center;">
1252.2
</td>
<td style="text-align:center;">
721.7
</td>
<td style="text-align:center;">
307.0
</td>
<td style="text-align:center;">
145.7
</td>
<td style="text-align:center;">
130.0
</td>
<td style="text-align:center;">
231.9
</td>
<td style="text-align:center;">
264.7
</td>
<td style="text-align:center;">
137.9
</td>
<td style="text-align:center;">
692.2
</td>
<td style="text-align:center;">
142.9
</td>
<td style="text-align:center;">
311.7
</td>
<td style="text-align:center;">
377.9
</td>
<td style="text-align:center;">
311.8
</td>
<td style="text-align:center;">
324.0
</td>
<td style="text-align:center;">
7259.3
</td>
<td style="text-align:left;">
1677.0
</td>
<td style="text-align:left;">
2142.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Albany
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
379.0
</td>
<td style="text-align:center;">
1346.9
</td>
<td style="text-align:center;">
825.5
</td>
<td style="text-align:center;">
394.5
</td>
<td style="text-align:center;">
200.4
</td>
<td style="text-align:center;">
215.2
</td>
<td style="text-align:center;">
381.0
</td>
<td style="text-align:center;">
376.4
</td>
<td style="text-align:center;">
257.0
</td>
<td style="text-align:center;">
919.6
</td>
<td style="text-align:center;">
140.6
</td>
<td style="text-align:center;">
402.7
</td>
<td style="text-align:center;">
327.9
</td>
<td style="text-align:center;">
569.2
</td>
<td style="text-align:center;">
594.3
</td>
<td style="text-align:center;">
2200.0
</td>
<td style="text-align:left;">
43750.0
</td>
<td style="text-align:left;">
11250.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Allegany
</td>
<td style="text-align:left;">
Western New York
</td>
<td style="text-align:center;">
137.5
</td>
<td style="text-align:center;">
357.1
</td>
<td style="text-align:center;">
214.3
</td>
<td style="text-align:center;">
61.2
</td>
<td style="text-align:center;">
107.1
</td>
<td style="text-align:center;">
109.1
</td>
<td style="text-align:center;">
166.7
</td>
<td style="text-align:center;">
140.3
</td>
<td style="text-align:center;">
124.4
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
133.3
</td>
<td style="text-align:center;">
96.8
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
114.2
</td>
<td style="text-align:center;">
15.6
</td>
<td style="text-align:left;">
2583.3
</td>
<td style="text-align:left;">
208.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Broome
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
307.7
</td>
<td style="text-align:center;">
821.1
</td>
<td style="text-align:center;">
463.7
</td>
<td style="text-align:center;">
312.2
</td>
<td style="text-align:center;">
183.2
</td>
<td style="text-align:center;">
187.8
</td>
<td style="text-align:center;">
172.4
</td>
<td style="text-align:center;">
296.6
</td>
<td style="text-align:center;">
221.9
</td>
<td style="text-align:center;">
803.9
</td>
<td style="text-align:center;">
152.9
</td>
<td style="text-align:center;">
482.8
</td>
<td style="text-align:center;">
1000.0
</td>
<td style="text-align:center;">
272.7
</td>
<td style="text-align:center;">
342.0
</td>
<td style="text-align:center;">
3166.7
</td>
<td style="text-align:left;">
3800.0
</td>
<td style="text-align:left;">
36333.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Cattaraugus
</td>
<td style="text-align:left;">
Western New York
</td>
<td style="text-align:center;">
107.9
</td>
<td style="text-align:center;">
236.8
</td>
<td style="text-align:center;">
82.6
</td>
<td style="text-align:center;">
114.9
</td>
<td style="text-align:center;">
107.0
</td>
<td style="text-align:center;">
86.0
</td>
<td style="text-align:center;">
187.5
</td>
<td style="text-align:center;">
116.8
</td>
<td style="text-align:center;">
91.5
</td>
<td style="text-align:center;">
625.0
</td>
<td style="text-align:center;">
13.3
</td>
<td style="text-align:center;">
41.2
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
107.8
</td>
<td style="text-align:center;">
342.9
</td>
<td style="text-align:left;">
571.4
</td>
<td style="text-align:left;">
36.6
</td>
</tr>
<tr>
<td style="text-align:left;">
Cayuga
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
152.9
</td>
<td style="text-align:center;">
620.7
</td>
<td style="text-align:center;">
186.7
</td>
<td style="text-align:center;">
150.6
</td>
<td style="text-align:center;">
95.2
</td>
<td style="text-align:center;">
76.9
</td>
<td style="text-align:center;">
150.0
</td>
<td style="text-align:center;">
147.7
</td>
<td style="text-align:center;">
99.2
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:center;">
218.8
</td>
<td style="text-align:center;">
243.9
</td>
<td style="text-align:center;">
384.6
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
175.7
</td>
<td style="text-align:center;">
300.0
</td>
<td style="text-align:left;">
4333.3
</td>
<td style="text-align:left;">
5000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Chautauqua
</td>
<td style="text-align:left;">
Western New York
</td>
<td style="text-align:center;">
95.4
</td>
<td style="text-align:center;">
161.6
</td>
<td style="text-align:center;">
95.9
</td>
<td style="text-align:center;">
92.0
</td>
<td style="text-align:center;">
80.3
</td>
<td style="text-align:center;">
97.7
</td>
<td style="text-align:center;">
60.6
</td>
<td style="text-align:center;">
101.2
</td>
<td style="text-align:center;">
65.9
</td>
<td style="text-align:center;">
333.3
</td>
<td style="text-align:center;">
137.3
</td>
<td style="text-align:center;">
64.8
</td>
<td style="text-align:center;">
20.1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
158.9
</td>
<td style="text-align:center;">
310.3
</td>
<td style="text-align:left;">
653.8
</td>
<td style="text-align:left;">
109.6
</td>
</tr>
<tr>
<td style="text-align:left;">
Chemung
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
281.9
</td>
<td style="text-align:center;">
615.4
</td>
<td style="text-align:center;">
281.3
</td>
<td style="text-align:center;">
247.4
</td>
<td style="text-align:center;">
182.6
</td>
<td style="text-align:center;">
404.5
</td>
<td style="text-align:center;">
666.7
</td>
<td style="text-align:center;">
290.1
</td>
<td style="text-align:center;">
252.3
</td>
<td style="text-align:center;">
929.8
</td>
<td style="text-align:center;">
94.3
</td>
<td style="text-align:center;">
102.6
</td>
<td style="text-align:center;">
43.5
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
391.9
</td>
<td style="text-align:center;">
800.0
</td>
<td style="text-align:left;">
2523.8
</td>
<td style="text-align:left;">
8000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Chenango
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
195.3
</td>
<td style="text-align:center;">
750.0
</td>
<td style="text-align:center;">
153.8
</td>
<td style="text-align:center;">
134.5
</td>
<td style="text-align:center;">
190.0
</td>
<td style="text-align:center;">
192.3
</td>
<td style="text-align:center;">
571.4
</td>
<td style="text-align:center;">
203.5
</td>
<td style="text-align:center;">
163.6
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
300.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
197.7
</td>
<td style="text-align:center;">
1800.0
</td>
<td style="text-align:left;">
2200.0
</td>
<td style="text-align:left;">
2111.1
</td>
</tr>
<tr>
<td style="text-align:left;">
Clinton
</td>
<td style="text-align:left;">
Eastern Adirondacks
</td>
<td style="text-align:center;">
97.0
</td>
<td style="text-align:center;">
370.4
</td>
<td style="text-align:center;">
154.4
</td>
<td style="text-align:center;">
84.6
</td>
<td style="text-align:center;">
44.6
</td>
<td style="text-align:center;">
48.8
</td>
<td style="text-align:center;">
266.7
</td>
<td style="text-align:center;">
98.3
</td>
<td style="text-align:center;">
85.2
</td>
<td style="text-align:center;">
2000.0
</td>
<td style="text-align:center;">
133.3
</td>
<td style="text-align:center;">
50.0
</td>
<td style="text-align:center;">
71.4
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
111.1
</td>
<td style="text-align:center;">
125.0
</td>
<td style="text-align:left;">
17000.0
</td>
<td style="text-align:left;">
666.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Columbia
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
152.4
</td>
<td style="text-align:center;">
304.3
</td>
<td style="text-align:center;">
188.4
</td>
<td style="text-align:center;">
206.7
</td>
<td style="text-align:center;">
114.3
</td>
<td style="text-align:center;">
51.9
</td>
<td style="text-align:center;">
100.0
</td>
<td style="text-align:center;">
163.2
</td>
<td style="text-align:center;">
147.1
</td>
<td style="text-align:center;">
521.7
</td>
<td style="text-align:center;">
88.2
</td>
<td style="text-align:center;">
60.0
</td>
<td style="text-align:center;">
130.4
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
153.8
</td>
<td style="text-align:center;">
1000.0
</td>
<td style="text-align:left;">
15000.0
</td>
<td style="text-align:left;">
250.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Cortland
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
157.4
</td>
<td style="text-align:center;">
478.3
</td>
<td style="text-align:center;">
191.9
</td>
<td style="text-align:center;">
111.9
</td>
<td style="text-align:center;">
118.1
</td>
<td style="text-align:center;">
113.2
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:center;">
162.7
</td>
<td style="text-align:center;">
164.5
</td>
<td style="text-align:center;">
222.2
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
74.1
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
203.4
</td>
<td style="text-align:center;">
1000.0
</td>
<td style="text-align:left;">
2600.0
</td>
<td style="text-align:left;">
583.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Delaware
</td>
<td style="text-align:left;">
Hudson Valley
</td>
<td style="text-align:center;">
252.1
</td>
<td style="text-align:center;">
312.5
</td>
<td style="text-align:center;">
306.7
</td>
<td style="text-align:center;">
190.5
</td>
<td style="text-align:center;">
212.1
</td>
<td style="text-align:center;">
340.9
</td>
<td style="text-align:center;">
400.0
</td>
<td style="text-align:center;">
225.2
</td>
<td style="text-align:center;">
172.0
</td>
<td style="text-align:center;">
1714.3
</td>
<td style="text-align:center;">
83.3
</td>
<td style="text-align:center;">
812.5
</td>
<td style="text-align:center;">
400.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
191.9
</td>
<td style="text-align:center;">
4000.0
</td>
<td style="text-align:left;">
19000.0
</td>
<td style="text-align:left;">
14000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Dutchess
</td>
<td style="text-align:left;">
Hudson Valley
</td>
<td style="text-align:center;">
297.9
</td>
<td style="text-align:center;">
1166.7
</td>
<td style="text-align:center;">
732.6
</td>
<td style="text-align:center;">
317.9
</td>
<td style="text-align:center;">
175.8
</td>
<td style="text-align:center;">
146.6
</td>
<td style="text-align:center;">
239.3
</td>
<td style="text-align:center;">
302.0
</td>
<td style="text-align:center;">
195.3
</td>
<td style="text-align:center;">
842.8
</td>
<td style="text-align:center;">
181.0
</td>
<td style="text-align:center;">
281.1
</td>
<td style="text-align:center;">
215.2
</td>
<td style="text-align:center;">
916.7
</td>
<td style="text-align:center;">
210.2
</td>
<td style="text-align:center;">
2263.2
</td>
<td style="text-align:left;">
8238.1
</td>
<td style="text-align:left;">
39666.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Erie
</td>
<td style="text-align:left;">
Western New York
</td>
<td style="text-align:center;">
337.6
</td>
<td style="text-align:center;">
750.6
</td>
<td style="text-align:center;">
594.5
</td>
<td style="text-align:center;">
375.5
</td>
<td style="text-align:center;">
191.1
</td>
<td style="text-align:center;">
215.9
</td>
<td style="text-align:center;">
303.9
</td>
<td style="text-align:center;">
325.8
</td>
<td style="text-align:center;">
128.0
</td>
<td style="text-align:center;">
336.2
</td>
<td style="text-align:center;">
61.6
</td>
<td style="text-align:center;">
467.2
</td>
<td style="text-align:center;">
237.8
</td>
<td style="text-align:center;">
338.2
</td>
<td style="text-align:center;">
386.0
</td>
<td style="text-align:center;">
2945.9
</td>
<td style="text-align:left;">
1252.5
</td>
<td style="text-align:left;">
8818.2
</td>
</tr>
<tr>
<td style="text-align:left;">
Essex/Hamilton
</td>
<td style="text-align:left;">
Eastern Adirondacks
</td>
<td style="text-align:center;">
55.4
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
106.1
</td>
<td style="text-align:center;">
27.5
</td>
<td style="text-align:center;">
48.1
</td>
<td style="text-align:center;">
19.2
</td>
<td style="text-align:center;">
142.9
</td>
<td style="text-align:center;">
53.6
</td>
<td style="text-align:center;">
46.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
87.6
</td>
<td style="text-align:center;">
200.0
</td>
<td style="text-align:left;">
3000.0
</td>
<td style="text-align:left;">
76.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Franklin
</td>
<td style="text-align:left;">
Eastern Adirondacks
</td>
<td style="text-align:center;">
146.0
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:center;">
170.0
</td>
<td style="text-align:center;">
168.1
</td>
<td style="text-align:center;">
52.2
</td>
<td style="text-align:center;">
106.4
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
150.0
</td>
<td style="text-align:center;">
142.9
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
212.1
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
346.2
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:left;">
300.0
</td>
<td style="text-align:left;">
357.1
</td>
</tr>
<tr>
<td style="text-align:left;">
Fulton
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
213.7
</td>
<td style="text-align:center;">
372.1
</td>
<td style="text-align:center;">
257.6
</td>
<td style="text-align:center;">
183.0
</td>
<td style="text-align:center;">
137.9
</td>
<td style="text-align:center;">
192.3
</td>
<td style="text-align:center;">
357.1
</td>
<td style="text-align:center;">
204.5
</td>
<td style="text-align:center;">
200.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
153.8
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:center;">
454.5
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
148.5
</td>
<td style="text-align:center;">
2000.0
</td>
<td style="text-align:left;">
3000.0
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Greene
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
158.3
</td>
<td style="text-align:center;">
357.1
</td>
<td style="text-align:center;">
245.3
</td>
<td style="text-align:center;">
150.8
</td>
<td style="text-align:center;">
70.7
</td>
<td style="text-align:center;">
125.0
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:center;">
158.9
</td>
<td style="text-align:center;">
145.7
</td>
<td style="text-align:center;">
857.1
</td>
<td style="text-align:center;">
83.3
</td>
<td style="text-align:center;">
153.8
</td>
<td style="text-align:center;">
150.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
134.5
</td>
<td style="text-align:center;">
5000.0
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
333.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Herkimer
</td>
<td style="text-align:left;">
Western Adirondacks
</td>
<td style="text-align:center;">
169.3
</td>
<td style="text-align:center;">
481.5
</td>
<td style="text-align:center;">
201.6
</td>
<td style="text-align:center;">
169.1
</td>
<td style="text-align:center;">
98.3
</td>
<td style="text-align:center;">
208.3
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
170.5
</td>
<td style="text-align:center;">
37.3
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
136.4
</td>
<td style="text-align:center;">
66.7
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
173.7
</td>
<td style="text-align:center;">
74.1
</td>
<td style="text-align:left;">
12000.0
</td>
<td style="text-align:left;">
666.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Jefferson
</td>
<td style="text-align:left;">
Western Adirondacks
</td>
<td style="text-align:center;">
126.5
</td>
<td style="text-align:center;">
270.0
</td>
<td style="text-align:center;">
141.6
</td>
<td style="text-align:center;">
122.2
</td>
<td style="text-align:center;">
90.7
</td>
<td style="text-align:center;">
83.8
</td>
<td style="text-align:center;">
87.0
</td>
<td style="text-align:center;">
132.1
</td>
<td style="text-align:center;">
106.1
</td>
<td style="text-align:center;">
226.0
</td>
<td style="text-align:center;">
47.6
</td>
<td style="text-align:center;">
87.7
</td>
<td style="text-align:center;">
75.0
</td>
<td style="text-align:center;">
62.5
</td>
<td style="text-align:center;">
230.5
</td>
<td style="text-align:center;">
714.3
</td>
<td style="text-align:left;">
3727.3
</td>
<td style="text-align:left;">
1333.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Lewis
</td>
<td style="text-align:left;">
Western Adirondacks
</td>
<td style="text-align:center;">
103.3
</td>
<td style="text-align:center;">
200.0
</td>
<td style="text-align:center;">
208.3
</td>
<td style="text-align:center;">
92.6
</td>
<td style="text-align:center;">
39.5
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
102.0
</td>
<td style="text-align:center;">
65.3
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
132.8
</td>
<td style="text-align:center;">
80.0
</td>
<td style="text-align:left;">
857.1
</td>
<td style="text-align:left;">
1000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Livingston
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
118.0
</td>
<td style="text-align:center;">
300.0
</td>
<td style="text-align:center;">
304.3
</td>
<td style="text-align:center;">
96.0
</td>
<td style="text-align:center;">
47.6
</td>
<td style="text-align:center;">
131.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
120.6
</td>
<td style="text-align:center;">
91.1
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
187.5
</td>
<td style="text-align:center;">
81.1
</td>
<td style="text-align:center;">
41.7
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
136.2
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:left;">
6000.0
</td>
<td style="text-align:left;">
3000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Madison
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
140.6
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:center;">
195.7
</td>
<td style="text-align:center;">
155.9
</td>
<td style="text-align:center;">
44.8
</td>
<td style="text-align:center;">
129.0
</td>
<td style="text-align:center;">
90.9
</td>
<td style="text-align:center;">
147.9
</td>
<td style="text-align:center;">
40.4
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
43.5
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
196.7
</td>
<td style="text-align:center;">
555.6
</td>
<td style="text-align:left;">
4000.0
</td>
<td style="text-align:left;">
294.1
</td>
</tr>
<tr>
<td style="text-align:left;">
Monroe
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
320.9
</td>
<td style="text-align:center;">
644.7
</td>
<td style="text-align:center;">
526.9
</td>
<td style="text-align:center;">
388.4
</td>
<td style="text-align:center;">
196.1
</td>
<td style="text-align:center;">
193.3
</td>
<td style="text-align:center;">
306.5
</td>
<td style="text-align:center;">
326.5
</td>
<td style="text-align:center;">
140.8
</td>
<td style="text-align:center;">
590.3
</td>
<td style="text-align:center;">
159.0
</td>
<td style="text-align:center;">
282.6
</td>
<td style="text-align:center;">
361.8
</td>
<td style="text-align:center;">
461.5
</td>
<td style="text-align:center;">
274.7
</td>
<td style="text-align:center;">
673.1
</td>
<td style="text-align:left;">
6000.0
</td>
<td style="text-align:left;">
38333.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Montgomery
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
203.4
</td>
<td style="text-align:center;">
482.8
</td>
<td style="text-align:center;">
315.8
</td>
<td style="text-align:center;">
139.8
</td>
<td style="text-align:center;">
130.7
</td>
<td style="text-align:center;">
209.7
</td>
<td style="text-align:center;">
136.4
</td>
<td style="text-align:center;">
183.0
</td>
<td style="text-align:center;">
151.7
</td>
<td style="text-align:center;">
750.0
</td>
<td style="text-align:center;">
41.7
</td>
<td style="text-align:center;">
277.8
</td>
<td style="text-align:center;">
157.1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
194.8
</td>
<td style="text-align:center;">
73.2
</td>
<td style="text-align:left;">
3600.0
</td>
<td style="text-align:left;">
333.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Nassau
</td>
<td style="text-align:left;">
Long Island
</td>
<td style="text-align:center;">
215.9
</td>
<td style="text-align:center;">
1153.5
</td>
<td style="text-align:center;">
741.3
</td>
<td style="text-align:center;">
287.4
</td>
<td style="text-align:center;">
113.3
</td>
<td style="text-align:center;">
97.5
</td>
<td style="text-align:center;">
162.1
</td>
<td style="text-align:center;">
215.8
</td>
<td style="text-align:center;">
95.9
</td>
<td style="text-align:center;">
707.0
</td>
<td style="text-align:center;">
133.2
</td>
<td style="text-align:center;">
216.2
</td>
<td style="text-align:center;">
36.4
</td>
<td style="text-align:center;">
243.5
</td>
<td style="text-align:center;">
211.3
</td>
<td style="text-align:center;">
10473.0
</td>
<td style="text-align:left;">
9232.8
</td>
<td style="text-align:left;">
15666.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Niagara
</td>
<td style="text-align:left;">
Western New York
</td>
<td style="text-align:center;">
235.4
</td>
<td style="text-align:center;">
569.9
</td>
<td style="text-align:center;">
392.3
</td>
<td style="text-align:center;">
217.0
</td>
<td style="text-align:center;">
136.1
</td>
<td style="text-align:center;">
191.6
</td>
<td style="text-align:center;">
207.5
</td>
<td style="text-align:center;">
228.2
</td>
<td style="text-align:center;">
157.2
</td>
<td style="text-align:center;">
605.5
</td>
<td style="text-align:center;">
120.0
</td>
<td style="text-align:center;">
363.6
</td>
<td style="text-align:center;">
280.7
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
272.6
</td>
<td style="text-align:center;">
1384.6
</td>
<td style="text-align:left;">
571.4
</td>
<td style="text-align:left;">
7500.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Oneida
</td>
<td style="text-align:left;">
Western Adirondacks
</td>
<td style="text-align:center;">
243.5
</td>
<td style="text-align:center;">
698.3
</td>
<td style="text-align:center;">
367.4
</td>
<td style="text-align:center;">
211.2
</td>
<td style="text-align:center;">
152.8
</td>
<td style="text-align:center;">
162.3
</td>
<td style="text-align:center;">
196.7
</td>
<td style="text-align:center;">
264.8
</td>
<td style="text-align:center;">
37.7
</td>
<td style="text-align:center;">
89.3
</td>
<td style="text-align:center;">
37.0
</td>
<td style="text-align:center;">
30.7
</td>
<td style="text-align:center;">
13.4
</td>
<td style="text-align:center;">
41.7
</td>
<td style="text-align:center;">
299.3
</td>
<td style="text-align:center;">
321.4
</td>
<td style="text-align:left;">
4391.3
</td>
<td style="text-align:left;">
2333.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Onondaga
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
312.9
</td>
<td style="text-align:center;">
910.0
</td>
<td style="text-align:center;">
527.0
</td>
<td style="text-align:center;">
311.2
</td>
<td style="text-align:center;">
180.4
</td>
<td style="text-align:center;">
193.0
</td>
<td style="text-align:center;">
245.5
</td>
<td style="text-align:center;">
319.0
</td>
<td style="text-align:center;">
148.6
</td>
<td style="text-align:center;">
601.6
</td>
<td style="text-align:center;">
86.7
</td>
<td style="text-align:center;">
242.6
</td>
<td style="text-align:center;">
276.3
</td>
<td style="text-align:center;">
404.8
</td>
<td style="text-align:center;">
352.6
</td>
<td style="text-align:center;">
1571.4
</td>
<td style="text-align:left;">
8642.9
</td>
<td style="text-align:left;">
120000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Ontario
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
167.0
</td>
<td style="text-align:center;">
640.0
</td>
<td style="text-align:center;">
285.7
</td>
<td style="text-align:center;">
154.7
</td>
<td style="text-align:center;">
83.3
</td>
<td style="text-align:center;">
178.6
</td>
<td style="text-align:center;">
100.0
</td>
<td style="text-align:center;">
165.7
</td>
<td style="text-align:center;">
127.2
</td>
<td style="text-align:center;">
478.3
</td>
<td style="text-align:center;">
105.3
</td>
<td style="text-align:center;">
177.6
</td>
<td style="text-align:center;">
171.1
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
196.4
</td>
<td style="text-align:center;">
23.8
</td>
<td style="text-align:left;">
8000.0
</td>
<td style="text-align:left;">
17500.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Orange
</td>
<td style="text-align:left;">
Hudson Valley
</td>
<td style="text-align:center;">
187.8
</td>
<td style="text-align:center;">
550.3
</td>
<td style="text-align:center;">
266.1
</td>
<td style="text-align:center;">
186.4
</td>
<td style="text-align:center;">
126.7
</td>
<td style="text-align:center;">
140.4
</td>
<td style="text-align:center;">
169.8
</td>
<td style="text-align:center;">
170.3
</td>
<td style="text-align:center;">
108.3
</td>
<td style="text-align:center;">
592.6
</td>
<td style="text-align:center;">
224.3
</td>
<td style="text-align:center;">
245.3
</td>
<td style="text-align:center;">
185.6
</td>
<td style="text-align:center;">
631.6
</td>
<td style="text-align:center;">
146.7
</td>
<td style="text-align:center;">
3772.7
</td>
<td style="text-align:left;">
1773.3
</td>
<td style="text-align:left;">
3272.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Orleans
</td>
<td style="text-align:left;">
Western New York
</td>
<td style="text-align:center;">
78.0
</td>
<td style="text-align:center;">
260.9
</td>
<td style="text-align:center;">
109.9
</td>
<td style="text-align:center;">
36.0
</td>
<td style="text-align:center;">
63.6
</td>
<td style="text-align:center;">
102.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
76.4
</td>
<td style="text-align:center;">
54.7
</td>
<td style="text-align:center;">
153.8
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
117.6
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
74.6
</td>
<td style="text-align:center;">
74.1
</td>
<td style="text-align:left;">
187.5
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Oswego
</td>
<td style="text-align:left;">
Western Adirondacks
</td>
<td style="text-align:center;">
110.2
</td>
<td style="text-align:center;">
246.4
</td>
<td style="text-align:center;">
156.6
</td>
<td style="text-align:center;">
67.4
</td>
<td style="text-align:center;">
109.0
</td>
<td style="text-align:center;">
85.3
</td>
<td style="text-align:center;">
133.3
</td>
<td style="text-align:center;">
111.8
</td>
<td style="text-align:center;">
63.1
</td>
<td style="text-align:center;">
111.1
</td>
<td style="text-align:center;">
83.3
</td>
<td style="text-align:center;">
68.2
</td>
<td style="text-align:center;">
50.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
127.8
</td>
<td style="text-align:center;">
83.3
</td>
<td style="text-align:left;">
1357.1
</td>
<td style="text-align:left;">
2818.2
</td>
</tr>
<tr>
<td style="text-align:left;">
Otsego
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
301.6
</td>
<td style="text-align:center;">
684.2
</td>
<td style="text-align:center;">
522.7
</td>
<td style="text-align:center;">
176.5
</td>
<td style="text-align:center;">
233.9
</td>
<td style="text-align:center;">
213.1
</td>
<td style="text-align:center;">
538.5
</td>
<td style="text-align:center;">
313.7
</td>
<td style="text-align:center;">
259.0
</td>
<td style="text-align:center;">
833.3
</td>
<td style="text-align:center;">
416.7
</td>
<td style="text-align:center;">
151.5
</td>
<td style="text-align:center;">
166.7
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
336.8
</td>
<td style="text-align:center;">
555.6
</td>
<td style="text-align:left;">
28000.0
</td>
<td style="text-align:left;">
809.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Putnam
</td>
<td style="text-align:left;">
Hudson Valley
</td>
<td style="text-align:center;">
112.9
</td>
<td style="text-align:center;">
1000.0
</td>
<td style="text-align:center;">
262.3
</td>
<td style="text-align:center;">
158.8
</td>
<td style="text-align:center;">
62.3
</td>
<td style="text-align:center;">
93.1
</td>
<td style="text-align:center;">
76.9
</td>
<td style="text-align:center;">
112.3
</td>
<td style="text-align:center;">
97.8
</td>
<td style="text-align:center;">
111.1
</td>
<td style="text-align:center;">
142.9
</td>
<td style="text-align:center;">
114.5
</td>
<td style="text-align:center;">
150.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
107.3
</td>
<td style="text-align:center;">
4666.7
</td>
<td style="text-align:left;">
6750.0
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Rensselaer
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
336.2
</td>
<td style="text-align:center;">
821.9
</td>
<td style="text-align:center;">
619.0
</td>
<td style="text-align:center;">
343.2
</td>
<td style="text-align:center;">
199.3
</td>
<td style="text-align:center;">
194.6
</td>
<td style="text-align:center;">
254.9
</td>
<td style="text-align:center;">
318.9
</td>
<td style="text-align:center;">
235.1
</td>
<td style="text-align:center;">
908.6
</td>
<td style="text-align:center;">
187.0
</td>
<td style="text-align:center;">
544.7
</td>
<td style="text-align:center;">
338.0
</td>
<td style="text-align:center;">
1136.4
</td>
<td style="text-align:center;">
612.5
</td>
<td style="text-align:center;">
7000.0
</td>
<td style="text-align:left;">
34000.0
</td>
<td style="text-align:left;">
8000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Rockland
</td>
<td style="text-align:left;">
Westchester/Rockland
</td>
<td style="text-align:center;">
81.1
</td>
<td style="text-align:center;">
382.1
</td>
<td style="text-align:center;">
100.4
</td>
<td style="text-align:center;">
95.2
</td>
<td style="text-align:center;">
51.5
</td>
<td style="text-align:center;">
58.4
</td>
<td style="text-align:center;">
55.7
</td>
<td style="text-align:center;">
69.2
</td>
<td style="text-align:center;">
32.3
</td>
<td style="text-align:center;">
354.8
</td>
<td style="text-align:center;">
66.9
</td>
<td style="text-align:center;">
134.6
</td>
<td style="text-align:center;">
338.6
</td>
<td style="text-align:center;">
333.3
</td>
<td style="text-align:center;">
38.3
</td>
<td style="text-align:center;">
1253.7
</td>
<td style="text-align:left;">
3781.2
</td>
<td style="text-align:left;">
20600.0
</td>
</tr>
<tr>
<td style="text-align:left;">
St Lawrence
</td>
<td style="text-align:left;">
Western Adirondacks
</td>
<td style="text-align:center;">
118.1
</td>
<td style="text-align:center;">
490.2
</td>
<td style="text-align:center;">
118.9
</td>
<td style="text-align:center;">
122.2
</td>
<td style="text-align:center;">
84.6
</td>
<td style="text-align:center;">
9.1
</td>
<td style="text-align:center;">
130.4
</td>
<td style="text-align:center;">
117.5
</td>
<td style="text-align:center;">
106.4
</td>
<td style="text-align:center;">
1500.0
</td>
<td style="text-align:center;">
131.6
</td>
<td style="text-align:center;">
127.0
</td>
<td style="text-align:center;">
115.4
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
200.0
</td>
<td style="text-align:center;">
51.7
</td>
<td style="text-align:left;">
307.7
</td>
<td style="text-align:left;">
76.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Saratoga
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
165.7
</td>
<td style="text-align:center;">
725.0
</td>
<td style="text-align:center;">
447.2
</td>
<td style="text-align:center;">
188.9
</td>
<td style="text-align:center;">
96.2
</td>
<td style="text-align:center;">
72.5
</td>
<td style="text-align:center;">
232.6
</td>
<td style="text-align:center;">
163.7
</td>
<td style="text-align:center;">
157.0
</td>
<td style="text-align:center;">
333.3
</td>
<td style="text-align:center;">
98.6
</td>
<td style="text-align:center;">
211.8
</td>
<td style="text-align:center;">
125.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
259.0
</td>
<td style="text-align:center;">
1083.3
</td>
<td style="text-align:left;">
13600.0
</td>
<td style="text-align:left;">
5250.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Schenectady
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
412.0
</td>
<td style="text-align:center;">
1024.1
</td>
<td style="text-align:center;">
648.0
</td>
<td style="text-align:center;">
389.5
</td>
<td style="text-align:center;">
226.9
</td>
<td style="text-align:center;">
330.6
</td>
<td style="text-align:center;">
583.3
</td>
<td style="text-align:center;">
387.8
</td>
<td style="text-align:center;">
264.0
</td>
<td style="text-align:center;">
828.5
</td>
<td style="text-align:center;">
365.4
</td>
<td style="text-align:center;">
660.1
</td>
<td style="text-align:center;">
894.7
</td>
<td style="text-align:center;">
2666.7
</td>
<td style="text-align:center;">
347.9
</td>
<td style="text-align:center;">
2200.0
</td>
<td style="text-align:left;">
40000.0
</td>
<td style="text-align:left;">
6000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Schoharie
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
256.1
</td>
<td style="text-align:center;">
750.0
</td>
<td style="text-align:center;">
244.4
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
131.6
</td>
<td style="text-align:center;">
296.3
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:center;">
260.7
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
166.7
</td>
<td style="text-align:center;">
100.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
258.1
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
1000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Schuyler
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
90.4
</td>
<td style="text-align:center;">
111.1
</td>
<td style="text-align:center;">
172.4
</td>
<td style="text-align:center;">
120.0
</td>
<td style="text-align:center;">
20.0
</td>
<td style="text-align:center;">
43.5
</td>
<td style="text-align:center;">
200.0
</td>
<td style="text-align:center;">
90.9
</td>
<td style="text-align:center;">
75.5
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
28.6
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:left;">
1250.0
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Seneca
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
112.9
</td>
<td style="text-align:center;">
352.9
</td>
<td style="text-align:center;">
123.7
</td>
<td style="text-align:center;">
114.3
</td>
<td style="text-align:center;">
51.0
</td>
<td style="text-align:center;">
162.2
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
112.7
</td>
<td style="text-align:center;">
87.3
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
272.7
</td>
<td style="text-align:center;">
117.6
</td>
<td style="text-align:center;">
111.1
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
146.7
</td>
<td style="text-align:center;">
24.7
</td>
<td style="text-align:left;">
5000.0
</td>
<td style="text-align:left;">
1600.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Steuben
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
181.5
</td>
<td style="text-align:center;">
600.0
</td>
<td style="text-align:center;">
222.7
</td>
<td style="text-align:center;">
138.6
</td>
<td style="text-align:center;">
125.5
</td>
<td style="text-align:center;">
200.0
</td>
<td style="text-align:center;">
142.9
</td>
<td style="text-align:center;">
179.3
</td>
<td style="text-align:center;">
160.6
</td>
<td style="text-align:center;">
1444.4
</td>
<td style="text-align:center;">
166.7
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
173.9
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
131.1
</td>
<td style="text-align:center;">
35.3
</td>
<td style="text-align:left;">
1303.4
</td>
<td style="text-align:left;">
2600.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Suffolk
</td>
<td style="text-align:left;">
Long Island
</td>
<td style="text-align:center;">
177.3
</td>
<td style="text-align:center;">
579.9
</td>
<td style="text-align:center;">
450.4
</td>
<td style="text-align:center;">
206.1
</td>
<td style="text-align:center;">
95.7
</td>
<td style="text-align:center;">
92.9
</td>
<td style="text-align:center;">
140.6
</td>
<td style="text-align:center;">
196.9
</td>
<td style="text-align:center;">
146.9
</td>
<td style="text-align:center;">
537.5
</td>
<td style="text-align:center;">
90.7
</td>
<td style="text-align:center;">
138.6
</td>
<td style="text-align:center;">
194.5
</td>
<td style="text-align:center;">
252.5
</td>
<td style="text-align:center;">
144.2
</td>
<td style="text-align:center;">
4610.2
</td>
<td style="text-align:left;">
11819.7
</td>
<td style="text-align:left;">
6040.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Sullivan
</td>
<td style="text-align:left;">
Hudson Valley
</td>
<td style="text-align:center;">
286.2
</td>
<td style="text-align:center;">
755.6
</td>
<td style="text-align:center;">
350.3
</td>
<td style="text-align:center;">
237.5
</td>
<td style="text-align:center;">
260.1
</td>
<td style="text-align:center;">
204.7
</td>
<td style="text-align:center;">
204.5
</td>
<td style="text-align:center;">
269.2
</td>
<td style="text-align:center;">
224.3
</td>
<td style="text-align:center;">
581.8
</td>
<td style="text-align:center;">
333.3
</td>
<td style="text-align:center;">
349.5
</td>
<td style="text-align:center;">
600.0
</td>
<td style="text-align:center;">
375.0
</td>
<td style="text-align:center;">
246.5
</td>
<td style="text-align:center;">
10500.0
</td>
<td style="text-align:left;">
3285.7
</td>
<td style="text-align:left;">
4000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Tioga
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
94.9
</td>
<td style="text-align:center;">
304.3
</td>
<td style="text-align:center;">
122.6
</td>
<td style="text-align:center;">
85.4
</td>
<td style="text-align:center;">
42.0
</td>
<td style="text-align:center;">
90.9
</td>
<td style="text-align:center;">
142.9
</td>
<td style="text-align:center;">
90.9
</td>
<td style="text-align:center;">
78.3
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
76.9
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
428.6
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
208.3
</td>
<td style="text-align:center;">
125.0
</td>
<td style="text-align:left;">
1500.0
</td>
<td style="text-align:left;">
1333.3
</td>
</tr>
<tr>
<td style="text-align:left;">
Tompkins
</td>
<td style="text-align:left;">
Central New York
</td>
<td style="text-align:center;">
184.0
</td>
<td style="text-align:center;">
730.8
</td>
<td style="text-align:center;">
430.0
</td>
<td style="text-align:center;">
183.7
</td>
<td style="text-align:center;">
75.7
</td>
<td style="text-align:center;">
115.9
</td>
<td style="text-align:center;">
128.2
</td>
<td style="text-align:center;">
175.7
</td>
<td style="text-align:center;">
152.1
</td>
<td style="text-align:center;">
464.3
</td>
<td style="text-align:center;">
126.3
</td>
<td style="text-align:center;">
288.5
</td>
<td style="text-align:center;">
275.9
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
263.0
</td>
<td style="text-align:center;">
300.0
</td>
<td style="text-align:left;">
6500.0
</td>
<td style="text-align:left;">
1666.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Ulster
</td>
<td style="text-align:left;">
Hudson Valley
</td>
<td style="text-align:center;">
300.0
</td>
<td style="text-align:center;">
836.1
</td>
<td style="text-align:center;">
464.8
</td>
<td style="text-align:center;">
336.3
</td>
<td style="text-align:center;">
184.4
</td>
<td style="text-align:center;">
187.3
</td>
<td style="text-align:center;">
271.4
</td>
<td style="text-align:center;">
292.4
</td>
<td style="text-align:center;">
251.4
</td>
<td style="text-align:center;">
795.5
</td>
<td style="text-align:center;">
214.3
</td>
<td style="text-align:center;">
338.6
</td>
<td style="text-align:center;">
388.9
</td>
<td style="text-align:center;">
307.7
</td>
<td style="text-align:center;">
202.0
</td>
<td style="text-align:center;">
2222.2
</td>
<td style="text-align:left;">
4476.2
</td>
<td style="text-align:left;">
4285.7
</td>
</tr>
<tr>
<td style="text-align:left;">
Warren
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
232.6
</td>
<td style="text-align:center;">
875.0
</td>
<td style="text-align:center;">
431.8
</td>
<td style="text-align:center;">
195.4
</td>
<td style="text-align:center;">
117.0
</td>
<td style="text-align:center;">
183.1
</td>
<td style="text-align:center;">
384.6
</td>
<td style="text-align:center;">
224.8
</td>
<td style="text-align:center;">
215.9
</td>
<td style="text-align:center;">
1200.0
</td>
<td style="text-align:center;">
150.0
</td>
<td style="text-align:center;">
470.6
</td>
<td style="text-align:center;">
307.7
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
193.1
</td>
<td style="text-align:center;">
3000.0
</td>
<td style="text-align:left;">
7250.0
</td>
<td style="text-align:left;">
2000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Washington
</td>
<td style="text-align:left;">
Capital/Saratoga
</td>
<td style="text-align:center;">
177.4
</td>
<td style="text-align:center;">
285.7
</td>
<td style="text-align:center;">
230.8
</td>
<td style="text-align:center;">
175.8
</td>
<td style="text-align:center;">
114.1
</td>
<td style="text-align:center;">
140.4
</td>
<td style="text-align:center;">
333.3
</td>
<td style="text-align:center;">
175.8
</td>
<td style="text-align:center;">
167.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
100.0
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
105.6
</td>
<td style="text-align:center;">
500.0
</td>
<td style="text-align:left;">
3000.0
</td>
<td style="text-align:left;">
6000.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Wayne
</td>
<td style="text-align:left;">
Finger Lakes
</td>
<td style="text-align:center;">
182.6
</td>
<td style="text-align:center;">
461.5
</td>
<td style="text-align:center;">
188.6
</td>
<td style="text-align:center;">
180.3
</td>
<td style="text-align:center;">
132.2
</td>
<td style="text-align:center;">
169.8
</td>
<td style="text-align:center;">
250.0
</td>
<td style="text-align:center;">
181.7
</td>
<td style="text-align:center;">
123.9
</td>
<td style="text-align:center;">
842.1
</td>
<td style="text-align:center;">
111.1
</td>
<td style="text-align:center;">
194.0
</td>
<td style="text-align:center;">
108.7
</td>
<td style="text-align:center;">
0.0
</td>
<td style="text-align:center;">
156.7
</td>
<td style="text-align:center;">
244.4
</td>
<td style="text-align:left;">
5000.0
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Westchester
</td>
<td style="text-align:left;">
Westchester/Rockland
</td>
<td style="text-align:center;">
329.2
</td>
<td style="text-align:center;">
1307.7
</td>
<td style="text-align:center;">
911.9
</td>
<td style="text-align:center;">
456.2
</td>
<td style="text-align:center;">
188.7
</td>
<td style="text-align:center;">
169.6
</td>
<td style="text-align:center;">
240.8
</td>
<td style="text-align:center;">
360.6
</td>
<td style="text-align:center;">
140.2
</td>
<td style="text-align:center;">
817.1
</td>
<td style="text-align:center;">
121.7
</td>
<td style="text-align:center;">
273.5
</td>
<td style="text-align:center;">
533.6
</td>
<td style="text-align:center;">
353.7
</td>
<td style="text-align:center;">
301.2
</td>
<td style="text-align:center;">
13181.8
</td>
<td style="text-align:left;">
10086.4
</td>
<td style="text-align:left;">
59066.7
</td>
</tr>
</tbody>
</table>
</div>
<p> </p>
</div>
</div>
</div>
<div id="exploratory-analysis" class="section level1">
<h1>Exploratory analysis</h1>
<hr />
<p>Our exploratory analysis was split into two categories - <a
href="ny_exploratory_analysis.html">New York State</a> and <a
href="nyc_exploratory_analysis.html">New York City</a>. We analyzed how
abortion rates may differ across our covariates (Age, Race/Ethnicity and
Financial Plan Status), using plots created via <code>plotly</code>. All
plots seen here have been made using <code>ggplot</code>. For
interactive plots, head over to the individual exploratory analyses
pages linked above!</p>
<div id="nyc-analysis-results" class="section level2">
<h2>NYC Analysis Results:</h2>
<p> </p>
<div id="age-1" class="section level4">
<h4>Age:</h4>
<p><img src="report_files/figure-html/unnamed-chunk-2-1.png" width="90%" /></p>
<p>From the bar plots, it is evident that those who are less than 20
years of age have the highest abortion rates across the boroughs in New
York City in 2019. These rates decrease as age categories increase. When
comparing between boroughs, Manhattan had the highest abortion rates in
categories <code>&lt;20</code> and <code>25-29</code>. Staten Island had
the lowest abortion rates overall, except for category
<code>20-24</code>. The highest abortion rate across all boroughs and
age categories was for Manhattan for <code>&lt; 20</code> with 1,964.9
induced abortions per 1,000 live births. The lowest abortion rate across
all boroughs and age categories was in Staten Island for
<code>35-39</code> with 130 induced abortions per 1,000 live births.</p>
</div>
<div id="raceethnicity-1" class="section level4">
<h4>Race/Ethnicity:</h4>
<p><img src="report_files/figure-html/unnamed-chunk-3-1.png" width="90%" /></p>
<p>From the bar plots, it is evident that those who identified as
Non-Hispanic Black had the highest abortion rates across all boroughs in
NYC. Among those who identified as Non-Hispanic Black, abortion rates
were highest in Manhattan with 1,228.3 induced abortions per 1,000 live
births. Those who identified as Non-Hispanic White and Non-Hispanic
Other had some of the lowest abortion rates in NYC. The lowest rates
across all boroughs and race groups was for those who identified as
Non-Hispanic White and lived in Brooklyn with a rates of 88.6 induced
abortions per 1,000 live births.</p>
</div>
<div id="financial-plan-status-1" class="section level4">
<h4>Financial Plan Status:</h4>
<p><img src="report_files/figure-html/unnamed-chunk-4-1.png" width="90%" /></p>
<p>From the bar plots, those who were categorized as having Other
Insurance had the highest abortion rates across all financial plans in
NYC with a rate of 62.86k induced abortions per 1000 live births. When
calculating abortion rates for financial plans, we manually calculated
these rates from (induced abortions/ live births)*1000 as they were not
provided like in other data sets. An noticeable trend is that those who
have induced abortions and those who give births tend to use different
insurance plans. People who give birth are unlikely to use
<code>Other Insurance</code> in comparison to those who have induced
abortions due to inherent differences in procedures. Those who used
<code>Self Pay</code> for induced abortions had a relatively high
abortion rates as well. This would make sense given the nature of the
procedure and possible restrictions by the health insurance plan to
cover abortions. Medicaid had the lowest abortion rates across all
financial plans, and the rates were lowest with 287 induced abortions
per 1,000 live births.</p>
<p> </p>
</div>
</div>
<div id="ny-state-analysis-results" class="section level2">
<h2>NY State Analysis Results</h2>
<p> </p>
<div id="age-2" class="section level4">
<h4>Age</h4>
<p><img src="report_files/figure-html/unnamed-chunk-5-1.png" width="90%" /></p>
<p>From the above plot, it is evident that within different categories
of age, the highest abortion rate per 1,000 live births is among those
that are below 20 years of age. We see a decline in induced abortion
rates among older people across all regions within New York State. The
highest abortion rate is found among those in New York City who are less
than 20 years of age with 7,677.5 induces abortions per 1,000 live
births. While New York city has higher abortion rates across most age
categories, we see that among those that are 35+, higher rates of
abortion are found among those in the Finger Lakes, Capital/Saratoga,
and Central New York regions.</p>
</div>
<div id="raceethnicity-2" class="section level4">
<h4>Race/Ethnicity</h4>
<p><img src="report_files/figure-html/unnamed-chunk-6-1.png" width="90%" /></p>
<p>When looking at abortion rates within different race/ethnicity
categories, we observe that the highest rates of abortion are among
those who identify as Non-Hispanic Black. The highest abortion rate is
among those residing in New York City and identify as Non-Hispanic Black
with 4,638.1 induced abortions per 1,000 live births. Hispanic
individuals also have high abortion rates, with the highest abortion
rate within this category among those that reside in the Capital/
Saratoga region (3,698.2 per 1000 live births).</p>
</div>
<div id="financial-plan-status-2" class="section level4">
<h4>Financial Plan Status</h4>
<p>Highest abortion rates are found among those enrolled in the
<code>Not Stated</code> insurance category, followed by the
<code>Other Insurance</code> category. The highest abortion rate, when
stratified by insurance enrollment, is found among those residing in the
Capital/Saratoga region, and reporting as <code>Not Stated</code>
insurance category with 168.1k induced abortions per 1,000 live births.
Within New York City, highest rates are found among those that are
enrolled in <code>Other Category</code> insurance plans with a rate of
150.1k induced abortions per 1,000 live births. Lowest rates of abortion
are found among those that are enrolled in Medicaid.</p>
<p> </p>
</div>
</div>
<div id="comparing-nyc-and-ny-state" class="section level2">
<h2>Comparing NYC and NY State</h2>
<p> </p>
<div id="ny-vs-nyc-age" class="section level4">
<h4>NY vs NYC Age</h4>
<p><img src="report_files/figure-html/unnamed-chunk-8-1.png" width="90%" /></p>
<p>From the bar plots, it is evident that those in New York City have
higher abortion rates compared to those in New York State across all age
categories. Rates seem to decrease as age categories increase for New
York City. However, for New York State, rates decrease from the &lt;20
to 35-39 age categories, and increase among those who are 40+. Rates
were highest among those who were &lt;20 years for both New York City
and New York State. Those &lt;20 years in New York State had the highest
rates across all categories of 1,491.4 abortions per 1,000 live
births.</p>
</div>
<div id="ny-vs.-nyc-race" class="section level4">
<h4>NY vs. NYC Race</h4>
<p><img src="report_files/figure-html/unnamed-chunk-9-1.png" width="90%" /></p>
<p>It is evident that those who identified as Non-Hispanic Black had the
highest abortion rates across all boroughs in New York City. Among those
who identified as Non-Hispanic Black, rates were highest in Manhattan
with 851.7 induced abortions per 1,000 live births. Those who identified
as Non-Hispanic White and Non-Hispanic Other had some of the lowest
abortion rates in New York City. The lowest rates across all boroughs
and race groups was for those who identified as Non-Hispanic White only
and lived in Brooklyn with a rates of 142.9 induced abortions per 1,000
live births.</p>
</div>
<div id="ny-vs.-nyc-financial-plans" class="section level4">
<h4>NY vs. NYC Financial Plans</h4>
<p><img src="report_files/figure-html/unnamed-chunk-10-1.png" width="90%" /></p>
<p>Rates were highest for those with <code>Other Insurance</code> in
both New York City and New York State and was higher in New York City
with 19.92k induced abortions per 1,000 live births. Rates were lowest
for those with Medicaid in both New York City and New York State and was
lower for those in New York State with 325.66 induced abortions per
1,000 live births.</p>
<p> </p>
</div>
</div>
</div>
<div id="statistical-analysis" class="section level1">
<h1>Statistical Analysis</h1>
<hr />
<p>In addition to conducting an exploratory analysis to assess how
abortion rates may have differed across boroughs, regions, and counties
and across different categories of our covariates (Age, Race/Ethnicity
and Financial Plan Status), we conducted a statistical analysis to
assess whether or not the differences observed in the data occurred only
by chance or due to our covariates. A proportion t-test was performed to
assess if abortion rates differed across geographical units. A
chi-squared test was performed to assess if abortion rates differed
across geographical units adjusting for our covariates. Because our
final tidy dataset reports abortion rates standardized by 1000 live
births, these points were converted back to abortion rates to run the
chi-squared tests.</p>
<div id="abortion-trends-in-ny-state" class="section level2">
<h2>Abortion Trends in NY State</h2>
<p> </p>
<div id="proportion-test---ny-state-regions" class="section level4">
<h4>Proportion Test - NY State Regions</h4>
<p><strong>Do overall abortion rates differ across NY state
regions?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
abortion rate per 1000 live births is the same across all NY state
regions.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
abortion rate per 1000 live births is not the same across all NY state
regions.</p>
<table>
<caption>Proportion T-Test for NY across all Regions</caption>
<thead>
<tr class="header">
<th align="left">Region</th>
<th align="center">Abortions per 1000 live births</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Central New York</td>
<td align="center">261.3792</td>
</tr>
<tr class="even">
<td align="left">Eastern Adirondacks</td>
<td align="center">113.8211</td>
</tr>
<tr class="odd">
<td align="left">Finger Lakes</td>
<td align="center">255.6622</td>
</tr>
<tr class="even">
<td align="left">Hudson Valley</td>
<td align="center">232.9893</td>
</tr>
<tr class="odd">
<td align="left">Long Island</td>
<td align="center">195.8584</td>
</tr>
<tr class="even">
<td align="left">New York City</td>
<td align="center">450.4669</td>
</tr>
<tr class="odd">
<td align="left">Saratoga</td>
<td align="center">289.1048</td>
</tr>
<tr class="even">
<td align="left">Westchester/Rockland</td>
<td align="center">238.3695</td>
</tr>
<tr class="odd">
<td align="left">Western Adirondacks</td>
<td align="center">164.5671</td>
</tr>
<tr class="even">
<td align="left">Western New York</td>
<td align="center">270.4626</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  10-sample test for equality of proportions without continuity
##  correction
## 
## data:  NY_totals$n out of NY_totals$total
## X-squared = 383.72, df = 9, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
##    prop 1    prop 2    prop 3    prop 4    prop 5    prop 6    prop 7    prop 8 
## 0.2613792 0.1138211 0.2556622 0.2329893 0.1958584 0.4504669 0.2891048 0.2383695 
##    prop 9   prop 10 
## 0.1645671 0.2704626</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that overall abortion rates per 1,000 live births
differs across NY state regions. Because this suggests that abortion
rates differs across NY state regions, we now can assess whether or not
this holds true across counties.</p>
</div>
<div id="proportion-test---ny-state-counties" class="section level4">
<h4>Proportion Test - NY State Counties</h4>
<p><strong>Do overall abortion rates differ across NY state
counties?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
abortion rates per 1000 live births is the same across all NY state
counties.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
abortion rates per 1000 live births is not the same across all NY state
counties.</p>
<table>
<caption>Proportion T-Test for NY across all Counties</caption>
<thead>
<tr class="header">
<th align="left">County</th>
<th align="center">Abortions per 1000 live births</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">623.3191</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">351.7053</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">537.4915</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">445.7356</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">275.5633</td>
</tr>
<tr class="even">
<td align="left">Albany</td>
<td align="center">378.9862</td>
</tr>
<tr class="odd">
<td align="left">Allegany</td>
<td align="center">137.5000</td>
</tr>
<tr class="even">
<td align="left">Broome</td>
<td align="center">307.6923</td>
</tr>
<tr class="odd">
<td align="left">Cattaraugus</td>
<td align="center">107.8788</td>
</tr>
<tr class="even">
<td align="left">Cayuga</td>
<td align="center">152.9255</td>
</tr>
</tbody>
</table>
<p>Only the first 10 counties are printed.</p>
<pre><code>## 
##  58-sample test for equality of proportions without continuity
##  correction
## 
## data:  NY_totals_counties$n out of NY_totals_counties$total
## X-squared = 4503.5, df = 57, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
##     prop 1     prop 2     prop 3     prop 4     prop 5     prop 6     prop 7 
## 0.62331910 0.35170533 0.53749154 0.44573557 0.27556326 0.37898624 0.13750000 
##     prop 8     prop 9    prop 10    prop 11    prop 12    prop 13    prop 14 
## 0.30769231 0.10787879 0.15292553 0.09538003 0.28187919 0.19532909 0.09695291 
##    prop 15    prop 16    prop 17    prop 18    prop 19    prop 20    prop 21 
## 0.15240084 0.15742794 0.25214900 0.29788811 0.33763819 0.05539359 0.14598540 
##    prop 22    prop 23    prop 24    prop 25    prop 26    prop 27    prop 28 
## 0.21372549 0.15833333 0.16932907 0.12652608 0.10333333 0.11796733 0.14057508 
##    prop 29    prop 30    prop 31    prop 32    prop 33    prop 34    prop 35 
## 0.32086440 0.20341880 0.21589681 0.23537941 0.24350260 0.31288344 0.16701031 
##    prop 36    prop 37    prop 38    prop 39    prop 40    prop 41    prop 42 
## 0.18778891 0.07801418 0.11021070 0.30158730 0.11292346 0.33623910 0.08110470 
##    prop 43    prop 44    prop 45    prop 46    prop 47    prop 48    prop 49 
## 0.11811812 0.16569201 0.41196979 0.25609756 0.09036145 0.11294766 0.18146718 
##    prop 50    prop 51    prop 52    prop 53    prop 54    prop 55    prop 56 
## 0.17732151 0.28620296 0.09493671 0.18402282 0.30000000 0.23264540 0.17741935 
##    prop 57    prop 58 
## 0.18263811 0.32919443</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that overall abortion rates per 1,000 live births
differs across NY state counties.</p>
</div>
<div id="chi-square-test---race-and-ny-state-counties"
class="section level4">
<h4>Chi Square Test - Race and NY State Counties</h4>
<p>Due to missing data, a chi-squared analysis was not run for race and
NY state regions.</p>
<p><strong>Do overall abortion rates differ across NY state counties by
race?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
expected abortion rates in each race category are the same across all NY
state counties.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
expected abortion rates in each race category are not the same across
all NY state counties.</p>
<table>
<caption>Chi-Square Test for Race and Counties</caption>
<thead>
<tr class="header">
<th align="left">County</th>
<th align="center">Hispanic</th>
<th align="center">Non-Hispanic White</th>
<th align="center">Non-Hispanic Black</th>
<th align="center">Non-Hispanic Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">500200</td>
<td align="center">369800</td>
<td align="center">734300</td>
<td align="center">419300</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">393100</td>
<td align="center">88600</td>
<td align="center">837700</td>
<td align="center">162500</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">519800</td>
<td align="center">320800</td>
<td align="center">1228300</td>
<td align="center">253200</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">329400</td>
<td align="center">155000</td>
<td align="center">895100</td>
<td align="center">273100</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">311700</td>
<td align="center">137900</td>
<td align="center">692200</td>
<td align="center">142900</td>
</tr>
<tr class="even">
<td align="left">Albany</td>
<td align="center">402700</td>
<td align="center">257000</td>
<td align="center">919600</td>
<td align="center">140600</td>
</tr>
<tr class="odd">
<td align="left">Broome</td>
<td align="center">482800</td>
<td align="center">221900</td>
<td align="center">803900</td>
<td align="center">152900</td>
</tr>
<tr class="even">
<td align="left">Cattaraugus</td>
<td align="center">41200</td>
<td align="center">91500</td>
<td align="center">625000</td>
<td align="center">13300</td>
</tr>
<tr class="odd">
<td align="left">Cayuga</td>
<td align="center">243900</td>
<td align="center">99200</td>
<td align="center">500000</td>
<td align="center">218800</td>
</tr>
<tr class="even">
<td align="left">Chautauqua</td>
<td align="center">64800</td>
<td align="center">65900</td>
<td align="center">333300</td>
<td align="center">137300</td>
</tr>
</tbody>
</table>
<p>Only the first 10 counties are printed.</p>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  NY_race_clean
## X-squared = 7989625, df = 135, p-value &lt; 2.2e-16</code></pre>
<pre><code>## [1] 163.1161</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that overall abortion rates in each race category
across counties is different.</p>
</div>
<div id="chi-square-test---finance-plans-and-ny-state-regions"
class="section level4">
<h4>Chi Square Test - Finance Plans and NY State Regions</h4>
<p><strong>Do overall abortion rates differ across NY state regions by
finance plan?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
expected abortion rates in each finance plan category are the same
across all NY state regions.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
expected abortion rates in each finance plan category are not the same
across all NY state regions.</p>
<table>
<caption>Chi-Square Test Finance Plan and Regions</caption>
<thead>
<tr class="header">
<th align="left">Region</th>
<th align="center">Medicaid</th>
<th align="center">Self-Pay</th>
<th align="center">Other Insurance</th>
<th align="center">Not Stated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Central New York</td>
<td align="center">307848.2</td>
<td align="center">1019047.62</td>
<td align="center">5209677</td>
<td align="center">8481012.7</td>
</tr>
<tr class="even">
<td align="left">Eastern Adirondacks</td>
<td align="center">135566.2</td>
<td align="center">18181.82</td>
<td align="center">1045455</td>
<td align="center">333333.3</td>
</tr>
<tr class="odd">
<td align="left">Finger Lakes</td>
<td align="center">240162.6</td>
<td align="center">123173.28</td>
<td align="center">1886076</td>
<td align="center">20950000.0</td>
</tr>
<tr class="even">
<td align="left">Hudson Valley</td>
<td align="center">175379.7</td>
<td align="center">3315789.47</td>
<td align="center">2962085</td>
<td align="center">9240000.0</td>
</tr>
<tr class="odd">
<td align="left">Long Island</td>
<td align="center">171955.0</td>
<td align="center">6869791.67</td>
<td align="center">10124294</td>
<td align="center">9162162.2</td>
</tr>
<tr class="even">
<td align="left">New York City</td>
<td align="center">401740.7</td>
<td align="center">8801213.96</td>
<td align="center">19924433</td>
<td align="center">1477876.1</td>
</tr>
<tr class="odd">
<td align="left">Saratoga</td>
<td align="center">375307.1</td>
<td align="center">827338.13</td>
<td align="center">15058824</td>
<td align="center">3484848.5</td>
</tr>
<tr class="even">
<td align="left">Westchester/Rockland</td>
<td align="center">162220.0</td>
<td align="center">5190000.00</td>
<td align="center">8300885</td>
<td align="center">49450000.0</td>
</tr>
<tr class="odd">
<td align="left">Western Adirondacks</td>
<td align="center">224686.3</td>
<td align="center">206030.15</td>
<td align="center">1729508</td>
<td align="center">821052.6</td>
</tr>
<tr class="even">
<td align="left">Western New York</td>
<td align="center">315989.7</td>
<td align="center">1031250.00</td>
<td align="center">1051360</td>
<td align="center">814433.0</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  NY_finance_clean
## X-squared = 90277426, df = 27, p-value &lt; 2.2e-16</code></pre>
<pre><code>## [1] 40.11327</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that overall abortion rates in each finance
category across regions is different.</p>
</div>
<div id="chi-square-test---finance-plan-and-ny-state-counties"
class="section level4">
<h4>Chi Square Test - Finance Plan and NY State Counties</h4>
<p><strong>Do overall abortion rates differ across NY state counties by
finance plan?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
expected abortion rates in each finance plan category are the same
across all NY state counties.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
expected abortion rates in each finance plan category are not the same
across all NY state counties.</p>
<table>
<caption>Chi-Square Test for Race and Counties</caption>
<thead>
<tr class="header">
<th align="left">County</th>
<th align="center">Hispanic</th>
<th align="center">Non-Hispanic White</th>
<th align="center">Non-Hispanic Black</th>
<th align="center">Non-Hispanic Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">500200</td>
<td align="center">369800</td>
<td align="center">734300</td>
<td align="center">419300</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">393100</td>
<td align="center">88600</td>
<td align="center">837700</td>
<td align="center">162500</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">519800</td>
<td align="center">320800</td>
<td align="center">1228300</td>
<td align="center">253200</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">329400</td>
<td align="center">155000</td>
<td align="center">895100</td>
<td align="center">273100</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">311700</td>
<td align="center">137900</td>
<td align="center">692200</td>
<td align="center">142900</td>
</tr>
<tr class="even">
<td align="left">Albany</td>
<td align="center">402700</td>
<td align="center">257000</td>
<td align="center">919600</td>
<td align="center">140600</td>
</tr>
<tr class="odd">
<td align="left">Broome</td>
<td align="center">482800</td>
<td align="center">221900</td>
<td align="center">803900</td>
<td align="center">152900</td>
</tr>
<tr class="even">
<td align="left">Cattaraugus</td>
<td align="center">41200</td>
<td align="center">91500</td>
<td align="center">625000</td>
<td align="center">13300</td>
</tr>
<tr class="odd">
<td align="left">Cayuga</td>
<td align="center">243900</td>
<td align="center">99200</td>
<td align="center">500000</td>
<td align="center">218800</td>
</tr>
<tr class="even">
<td align="left">Chautauqua</td>
<td align="center">64800</td>
<td align="center">65900</td>
<td align="center">333300</td>
<td align="center">137300</td>
</tr>
</tbody>
</table>
<p>Only the first 10 counties are printed.</p>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  NY_finance_counties
## X-squared = 7989625, df = 135, p-value &lt; 2.2e-16</code></pre>
<pre><code>## [1] 163.1161</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that overall abortion rates in each finance
category across counties is different.</p>
</div>
<div id="chi-square-test---age-and-ny-state-counties"
class="section level4">
<h4>Chi Square Test - Age and NY State Counties</h4>
<p>Due to missing data, a chi-squared analysis was not run for race and
NY state regions.</p>
<p><strong>Do overall abortion rates differ across NY state counties by
age?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
expected abortion rates in each age category are the same across all NY
state counties.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
expected abortion rates in each age category are not the same across all
NY state counties.</p>
<table>
<caption>Chi-Square Test for Age and Counties</caption>
<thead>
<tr class="header">
<th align="left">County</th>
<th align="center">&lt; 20 years</th>
<th align="center">20-24 years</th>
<th align="center">25-29 years</th>
<th align="center">30-34 years</th>
<th align="center">35-39 years</th>
<th align="center">40+ years</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">1291900</td>
<td align="center">860800</td>
<td align="center">605000</td>
<td align="center">497100</td>
<td align="center">443100</td>
<td align="center">447800</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">1388400</td>
<td align="center">515300</td>
<td align="center">412600</td>
<td align="center">251800</td>
<td align="center">210500</td>
<td align="center">242800</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">1964900</td>
<td align="center">1768600</td>
<td align="center">988100</td>
<td align="center">312200</td>
<td align="center">256500</td>
<td align="center">312000</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">1780100</td>
<td align="center">915600</td>
<td align="center">476500</td>
<td align="center">282900</td>
<td align="center">275700</td>
<td align="center">396400</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">1252200</td>
<td align="center">721700</td>
<td align="center">307000</td>
<td align="center">145700</td>
<td align="center">130000</td>
<td align="center">231900</td>
</tr>
<tr class="even">
<td align="left">Albany</td>
<td align="center">1346900</td>
<td align="center">825500</td>
<td align="center">394500</td>
<td align="center">200400</td>
<td align="center">215200</td>
<td align="center">381000</td>
</tr>
<tr class="odd">
<td align="left">Allegany</td>
<td align="center">357100</td>
<td align="center">214300</td>
<td align="center">61200</td>
<td align="center">107100</td>
<td align="center">109100</td>
<td align="center">166700</td>
</tr>
<tr class="even">
<td align="left">Broome</td>
<td align="center">821100</td>
<td align="center">463700</td>
<td align="center">312200</td>
<td align="center">183200</td>
<td align="center">187800</td>
<td align="center">172400</td>
</tr>
<tr class="odd">
<td align="left">Cattaraugus</td>
<td align="center">236800</td>
<td align="center">82600</td>
<td align="center">114900</td>
<td align="center">107000</td>
<td align="center">86000</td>
<td align="center">187500</td>
</tr>
<tr class="even">
<td align="left">Cayuga</td>
<td align="center">620700</td>
<td align="center">186700</td>
<td align="center">150600</td>
<td align="center">95200</td>
<td align="center">76900</td>
<td align="center">150000</td>
</tr>
</tbody>
</table>
<p>Only the first 10 counties are printed.</p>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  NY_age_clean
## X-squared = 10730198, df = 275, p-value &lt; 2.2e-16</code></pre>
<pre><code>## [1] 314.6784</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that overall abortion rates in each age category
across counties is different.</p>
<p> </p>
</div>
</div>
<div id="abortion-trends-in-nyc" class="section level2">
<h2>Abortion Trends in NYC</h2>
<p> </p>
<div id="proportion-t-test---boroughs" class="section level4">
<h4>Proportion T-Test - Boroughs</h4>
<p><strong>Do overall abortion rates differ across
boroughs?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
abortion rate per 1,000 live births is the same across all boroughs.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
abortion rate per 1,000 live births is not the same across all
boroughs.</p>
<table>
<caption>Proportion T-Test for NYC across all Boroughs</caption>
<thead>
<tr class="header">
<th align="left">Borough</th>
<th align="center">Abortion Rate per 1000 live births</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">623.3191</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">351.7053</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">537.4915</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">445.7356</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">275.5633</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  5-sample test for equality of proportions without continuity correction
## 
## data:  abortion_totals_borough$n out of abortion_totals_borough$total
## X-squared = 314.57, df = 4, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
##    prop 1    prop 2    prop 3    prop 4    prop 5 
## 0.6233191 0.3517053 0.5374915 0.4457356 0.2755633</code></pre>
<p>From the above results, the p-value is <strong>less than the 5% level
of significance</strong>. Therefore, we <strong>reject the null
hypothesis</strong>. The data provides sufficient evidence to support
the hypothesis that overall abortion rates per 1000 births live differs
across boroughs.</p>
</div>
<div id="chi-square-test---race-and-boroughs" class="section level4">
<h4>Chi Square Test - Race and Boroughs</h4>
<p><strong>Do overall abortion rates differ across boroughs by
race?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
expected abortion rate in each race category are the same across all
boroughs.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
expected abortion rate in each race category are not the same across all
boroughs.</p>
<table>
<caption>Chi-Square Test for Race and Boroughs</caption>
<thead>
<tr class="header">
<th align="left">Borough</th>
<th align="center">Hispanic</th>
<th align="center">Non-Hispanic White</th>
<th align="center">Non-Hispanic Black</th>
<th align="center">Non-Hispanic Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">500200</td>
<td align="center">369800</td>
<td align="center">734300</td>
<td align="center">419300</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">393100</td>
<td align="center">88600</td>
<td align="center">837700</td>
<td align="center">162500</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">519800</td>
<td align="center">320800</td>
<td align="center">1228300</td>
<td align="center">253200</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">329400</td>
<td align="center">155000</td>
<td align="center">895100</td>
<td align="center">273100</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">311700</td>
<td align="center">137900</td>
<td align="center">692200</td>
<td align="center">142900</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  abortion_race_clean
## X-squared = 349146, df = 12, p-value &lt; 2.2e-16</code></pre>
<pre><code>## [1] 21.02607</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, we <strong>reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that the abortion rate in each race category
across boroughs is different.</p>
</div>
<div id="chi-square-test---finance-plan-and-boroughs"
class="section level4">
<h4>Chi Square Test - Finance Plan and Boroughs</h4>
<p><strong>Do overall abortion rates differ across boroughs by finance
plan?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
expected abortion rates in each finance plan category are the same
across all boroughs.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
expected abortions rates in each finance plan category are not the same
across all boroughs.</p>
<table>
<caption>Chi-Square Test for Finance Plan and Boroughs</caption>
<thead>
<tr class="header">
<th align="left">Borough</th>
<th align="center">Medicaid</th>
<th align="center">Self-Pay</th>
<th align="center">Other Insurance</th>
<th align="center">Not Stated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">488454.1</td>
<td align="center">6150943</td>
<td align="center">31915094</td>
<td align="center">1498069.5</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">286998.5</td>
<td align="center">8644444</td>
<td align="center">19678414</td>
<td align="center">2058823.5</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">708360.2</td>
<td align="center">31285714</td>
<td align="center">62864407</td>
<td align="center">576576.6</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">408648.3</td>
<td align="center">6299180</td>
<td align="center">33990991</td>
<td align="center">3519480.5</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">323994.6</td>
<td align="center">7259259</td>
<td align="center">1676976</td>
<td align="center">2142857.1</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  abortion_finance_clean
## X-squared = 28441079, df = 12, p-value &lt; 2.2e-16</code></pre>
<pre><code>## [1] 21.02607</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that the abortion rates in each finance category
across borough is different.</p>
</div>
<div id="chi-square-test---age-and-boroughs" class="section level4">
<h4>Chi Square Test - Age and Boroughs</h4>
<p><strong>Do overall abortion rates differ across boroughs by
age?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
expected abortion rates in each age category are the same across all
boroughs.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
expected abortion rates in each age category are not the same across all
boroughs.</p>
<table>
<caption>Chi-Square Test for Age and Boroughs</caption>
<thead>
<tr class="header">
<th align="left">Borough</th>
<th align="center">&lt; 20 years</th>
<th align="center">20-24 years</th>
<th align="center">25-29 years</th>
<th align="center">30-34 years</th>
<th align="center">35-39 years</th>
<th align="center">40+ years</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="center">1291900</td>
<td align="center">860800</td>
<td align="center">605000</td>
<td align="center">497100</td>
<td align="center">443100</td>
<td align="center">447800</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="center">1388400</td>
<td align="center">515300</td>
<td align="center">412600</td>
<td align="center">251800</td>
<td align="center">210500</td>
<td align="center">242800</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="center">1964900</td>
<td align="center">1768600</td>
<td align="center">988100</td>
<td align="center">312200</td>
<td align="center">256500</td>
<td align="center">312000</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="center">1780100</td>
<td align="center">915600</td>
<td align="center">476500</td>
<td align="center">282900</td>
<td align="center">275700</td>
<td align="center">396400</td>
</tr>
<tr class="odd">
<td align="left">Staten Island</td>
<td align="center">1252200</td>
<td align="center">721700</td>
<td align="center">307000</td>
<td align="center">145700</td>
<td align="center">130000</td>
<td align="center">231900</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  abortion_age_clean
## X-squared = 881655, df = 20, p-value &lt; 2.2e-16</code></pre>
<pre><code>## [1] 31.41043</code></pre>
<p>From the above results, <strong><span
class="math inline">\(X^2\)</span> is greater than the test-statistic at
the 5% level of significance</strong>. Therefore, <strong>we reject the
null hypothesis.</strong> The data provides sufficient evidence to
support the hypothesis that the overall abortion rate in each age
category across borough is different.</p>
<p> </p>
</div>
</div>
<div id="abortions-rates-comparing-nyc-and-ny-state"
class="section level2">
<h2>Abortions Rates Comparing NYC and NY State</h2>
<p> </p>
<div id="proportion-t-test" class="section level4">
<h4>Proportion T-test</h4>
<p><strong>Do overall abortion rates differ between NYC and NY
state?</strong></p>
<p><strong><span class="math inline">\(H_0\)</span></strong>: The
abortion rate per 1,000 births is the same between NYC and NY state.</p>
<p><strong><span class="math inline">\(H_1\)</span></strong>: The
abortion rate per 1,000 births differs between NYC and NY state.</p>
<table>
<caption>Proportion T-Test for NYC and NY State</caption>
<thead>
<tr class="header">
<th align="left">Region</th>
<th align="center">Abortion Rate per 1000 births</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">New York State</td>
<td align="center">336.5029</td>
</tr>
<tr class="even">
<td align="left">New York City</td>
<td align="center">450.4669</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  abortion_totals$n out of abortion_totals$total
## X-squared = 26.735, df = 1, p-value = 2.334e-07
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.15749190 -0.07043623
## sample estimates:
##    prop 1    prop 2 
## 0.3365029 0.4504669</code></pre>
<p>From the above results, the p-value is <strong>less than the 5% level
of significance.</strong> Therefore, we <strong>reject the null
hypothesis.</strong> The data provides sufficient evidence to support
the hypothesis that the abortion rate per 1000 births differs between
NYC and NY state.</p>
<p> </p>
</div>
</div>
</div>
<div id="limiations" class="section level1">
<h1>Limiations</h1>
<hr />
<p>There were a couple of limitations in our project including the
amount of limited abortion data in some of the counties. For the race
dataset specifically, some of the data was noted as suppressed due to
confidentiality. As a result, we had to omit Eastern and Western
Adirondacks from our statistical analysis, despite the possibility that
there might be valuable information in these regions. Similarly, for the
financial plan dataset, there were some finance plans that had very
small cell counts. The plans with small cell counts were eventually
omitted as they were not included in the live birth data set, the
denominator to calculate abortion rates. As a result, the statistical
analysis for financial plan may not show the full scale of the
differences between the plans.</p>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<hr />
<p>Based on our statistical analysis, we found that abortion rates in
2019 are significantly different across New York City boroughs, New York
state regions, and New York state counties. Abortion rates in 2019 are
also significantly different across the aforementioned geographical
units adjusting for the covariates of interest: race, financial plan,
and age. In addition, abortion rates in 2019 are significantly different
between New York City and New York state. These results are what we
expected due to the history of reproductive rights and existing
socioeconomic disparities in the United States. More specifically,
people of color, people with higher financial burdens, and people who
are younger are most impacted by the state of abortion access. In New
York City, where there have been policies put into place to promote
reproductive rights, there are still disparities in abortion access due
to deeply rooted systems of oppression. From our exploratory analysis,
we found that the highest abortion rate is found among those in the
Bronx among those who are Non-Hispanic Black. With respect to insurance
plans, the lowest abortion rate is found among those with Medicaid,
which is an insurance plan used by those with a low income. With respect
to age, the highest abortion rate is found among those who are younger
than 20 years of age.</p>
<p>These insights are useful for state and local governments to
determine where and to whom to allocate more social services and
resources to promote reproductive health. Future analyses can focus on
exploring the trends and distribution of abortion rates in New York City
and New York State on a neighborhood level, mapping the locations of
abortion clinics and other sexual and reproductive services, and
repeating these exploratory and statistical analyses as data for recent
years are released.</p>
<p> </p>
</div>
<div id="additional-resources-related-work" class="section level1">
<h1>Additional Resources/ Related Work</h1>
<hr />
<p>From a public health stand point, reproductive rights are basic human
rights, and women should be allowed to have full autonomy on decisions
regarding their bodies. However, the issue at hand is very complicated,
and it is important to consider both sides of the argument.</p>
<p>Regardless of the stance people take on abortions, studies and past
data has found that reproductive justice is inextricably bound to
discrimination and inequality. As residents of New York City, we wanted
to analyze the trends in abortion, and how it might be affected by
factors such as race/ethnicity, financial plan status and age to better
understand differences in trends.</p>
<p>Here is some recent information on abortion clinics/ laws/ and
facts:</p>
<ul>
<li><p>In New York City, call the NYC Abortion Access Hub at <a
href="tel:18776922482">1-877-NYC-AHUB</a> or <a
href="tel:18776922482">1-877-692-2482</a></p></li>
<li><p><a
href="https://www.abortionfinder.org/">AbortionFinder.org</a></p></li>
<li><p><a
href="https://www.plannedparenthood.org/abortion-access">Planned
Parenthood</a></p></li>
<li><p><a
href="https://reproductiverights.org/maps/abortion-laws-by-state/">after
Roe Fell: Abortion Laws by State</a></p></li>
<li><p><a
href="https://www.guttmacher.org/state-policy/explore/overview-abortion-laws">Guttmacher
Institute</a></p></li>
<li><p><a
href="https://www.nytimes.com/2022/07/08/nyregion/abortion-new-york-roe.html">What’s
Next for Abortion Rights in New York?</a></p></li>
<li><p><a href="https://abortionfunds.org/">National Network of Abortion
Funds</a></p></li>
<li><p><a
href="https://lozierinstitute.org/abortion-reporting-new-york-city-2019/">Abortion
Reporting: New York City (2019)</a></p></li>
</ul>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
