---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include = FALSE}
library(tidyverse)
library(plotly)
```


```{r data import, include = FALSE}
merged_data = read_csv("data/master.csv")

merged_data = 
  merged_data %>% 
    pivot_longer(
      age_less_20:age_plus_40,
      names_to = "age", 
      values_to = "abortion",
      names_prefix = "age_"
    ) %>% 
    mutate(
      age = replace(age, age == "less_20", "<20"),
      age = replace(age, age == "20_24", "20-24"),
      age = replace(age, age == "25_29", "25-29"),
      age = replace(age, age == "30_34", "30-34"),
      age = replace(age, age == "35_39", "35-39"),
      age = replace(age, age == "plus_40", "40+"),
      age = factor(age)
    )
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r sidebar}
age = merged_data %>% distinct(age) %>% pull()

selectInput(
  inputId = "age_choice",
  label = h3("Age"),
  choices = age,
  selected = "<20"
)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

renderPlotly({
  merged_data %>% 
    filter(age == input[["age_choice"]]) %>% 
    mutate(borough = fct_reorder(borough, abortion)) %>% 
    plot_ly(x = ~borough, y = ~abortion, color = ~borough, colors = "viridis", type = "bar") %>% 
    layout(
      title = 'Abortions Ratios in New York State Counties', 
      xaxis = list(title = "County"),
      yaxis = list(title = 'Number of Induced Abortions 
                   per 1,000 Live Births'))
}) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint({
input[["age_choice"]]
})
```

### Chart C

```{r}
renderPrint({
input[["age_choice"]]
})
```

