---
title: "Statistical Analysis of Abortion Trends Among NYC and Compared to NY State"
---

```{r setup, message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r data, message=FALSE, include=FALSE}
abortion_data = read_csv("data/abortion_data.csv")
abortion_race = read_csv("data/abortion_race.csv")
abortion_finance = read_csv("data/abortion_finance.csv")
```

## *Abortions Rates Comparing NYC and NY State*

*Proportion T-test*

Do overall abortion rates differ between NYC and NY state?

H0: The number of abortions per 1000 births is the same between NYC and NY state.

H1: The number of abortions per 1000 births differs between NYC and NY state.

```{r prop}
# Tidy data
abortion_totals =
  abortion_data %>%
  select(borough, total) %>%
  head(2) %>%
  pivot_wider(
    names_from = "borough",
    values_from = "total") %>%
  janitor::clean_names()

# Run prop t-test
prop.test(abortion_totals$new_york_state, abortion_totals$new_york_city,
          p = NULL, alternative = "two.sided") %>%
  broom::tidy() %>%
  knitr::kable(digits = 3)
```


## *Abortion Trends in NYC*

*Chi Square Test - Race and Boroughs*

H0: Abortions rates

```{r chi-sq, }

```


