---
title: "plotly"
author: "Maisie Sun"
date: "2022-12-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(janitor)
library(ggridges)
library(patchwork)
library(readxl)
library("writexl")
library(rvest)
library(httr)
library(dplyr)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data Import

Importing master data that has been already cleaned. 

```{r data_import}
data = read_csv(file = "data/master.csv") %>%
  janitor::clean_names()
```

## NYC Age

From the master spreadsheet, we selected the columns and rows we will be using to analyze induced abortions by age categories. 

We used `pivot_longer` to 

```{r}
age = 
  data %>%
  select(1:7) %>%
  slice(1:5)

age %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  mutate(age = factor(age, levels = c("age_less_20", "age_20_24", "age_25_29", "age_30_34", "age_35_39", "age_plus_40"))) %>% 
  plot_ly(x = ~age, y = ~abortion, color = ~borough, type = "bar", colors = "viridis") %>%   
  layout(title = 'Abortion Ratios by Age for Boroughs in New York City', yaxis = list(title = 'Number of Induced Abortions per 1,000 Live Births'))
```

## NYC Race

```{r}
age = 
  data %>%
  select(1:7) %>%
  slice(1:5)
```

