---
title: "abortion_total"
author: "Maisie Sun"
date: "2022-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(janitor)
library(ggridges)
library(patchwork)
library(readxl)
library("writexl")
library(rvest)
library(httr)
library(dplyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Import Datasets

```{r data_import_age, echo = FALSE}
abortion_race_h = read_csv("./data/abortion_race_h.csv") %>%
  janitor::clean_names()
abortion_race_nh = read_csv("./data/abortion_race_nh.csv") %>%
  janitor::clean_names()
abortion_age = read_csv("./data/abortion_age.csv") %>%
  janitor::clean_names()
abortion_finance = read_csv("./data/abortion_finance.csv") %>%
  janitor::clean_names()

NY_age = read_csv("./data/NY_age.csv") %>%
  janitor::clean_names()
NY_finance = read_csv("./data/NY_finance.csv") %>%
  janitor::clean_names()
NY_race_h = read_csv("./data/NY_race_h.csv") %>%
  janitor::clean_names()
NY_race_nh = read_csv("./data/NY_race_nh.csv") %>%
  janitor::clean_names()
```

## Merge Datasets

```{r}
abortion_race = full_join(abortion_race_h, abortion_race_nh)
write_csv(abortion_race, file = "data/abortion_race.csv")

merged_data_1 = full_join(abortion_race, abortion_age)
merged_data_2 = full_join(merged_data_1, abortion_finance)

merged_data_3 = full_join(merged_data_2, NY_race_h)
merged_data_4 = full_join(merged_data_3, NY_race_nh)
merged_data_5 = full_join(merged_data_4, NY_finance)
merged_data_6 = full_join(merged_data_4, NY_age)

write_csv(merged_data_6, file = "data/abortion_data.csv")

```

