---
title: "Abortion by Age"
date: "2022-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(janitor)
library(ggridges)
library(patchwork)
library(readxl)
library("writexl")
library(rvest)
library(httr)
library(dplyr)
library(plotly)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Maternal Age
Get the data for age

```{r data_import_age}
url = "https://www.health.ny.gov/statistics/vital_statistics/2019/table21.htm"

induced_abortion = 
  read_html(url) %>%
  html_table(header = FALSE) %>%
  first() %>%
  janitor::clean_names()

```

data cleaning for age

```{r data_cleaning_age}
clean_age = 
  induced_abortion %>%
  select(1:8) %>%
  purrr::set_names(c("borough", "total", "age_less_20", "age_20_24", "age_25_29", "age_30_34", "age_35_39", "age_plus_40")) %>%
  slice(6:11) %>%
  mutate(
    borough = str_replace(borough, "Kings", "Brooklyn"),
    borough = str_replace(borough, "New York City", "New_York_City"),
    borough = str_replace(borough, "New York", "Manhattan"),
    borough = str_replace(borough, "Richmond", "Staten_Island"),
    total = str_replace(total, ",", ""),
    age_less_20 = str_replace(age_less_20, ",", ""),
    age_20_24 = str_replace(age_20_24, ",", ""),
    age_25_29 = str_replace(age_25_29, ",", ""),
    age_30_34 = str_replace(age_30_34, ",", ""),
    age_35_39 = str_replace(age_35_39, ",", ""),
    age_plus_40 = str_replace(age_plus_40, ",", "")
    ) %>%
  mutate_at(c("total", "age_less_20", "age_20_24", "age_25_29", "age_30_34", "age_35_39", "age_plus_40"), as.numeric)
  

```

ggplot: induced abortion vs maternal age

```{r age_plot}
total_abortion_age_plot = 
  clean_age %>%
  slice_head(n = 1) %>%
  select(-total) %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion)) + 
  geom_point() + geom_line(group = abortion) + 
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10))

clean_age %>%
  slice_head(n = 1) %>%
  select(-total) %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  mutate(age = fct_reorder(age)) %>% 
plot_ly(
    x = ~age, y = ~abortion, type = "scatter", mode = "line", alpha = 0.5)





abortion_age_wtotal_plot = 
  clean_age %>%
  select(-total) %>%
  slice(-1) %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion, fill = borough)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_point(data = total_abortion_age) +
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10) )

matrix_age_total = 
  total_abortion_age_plot + abortion_age_wtotal_plot

abortion_age_plot = 
  clean_age %>%
  select(-total) %>%
  slice(-1) %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion, fill = borough)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10) )

age_bronx = 
clean_age %>%
  select(-total) %>%
  filter(borough == "Bronx") %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10) )

age_bronx

age_brooklyn = 
clean_age %>%
  select(-total) %>%
  filter(borough == "Brooklyn") %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10) )

age_brooklyn

age_manhattan = 
clean_age %>%
  select(-total) %>%
  filter(borough == "Manhattan") %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10) )

age_manhattan

age_queens = 
clean_age %>%
  select(-total) %>%
  filter(borough == "Queens") %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10) )

age_queens

age_si = 
clean_age %>%
  select(-total) %>%
  filter(borough == "Staten_Island") %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion, fill = borough)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(
    title = "Number of Induced Abortions by Woman's Age and Borough, 2019",
    x = "Woman's age categories",
    y = "Number of Induced Abortions"
  ) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10) )

age_si

matrix_age = 
  (abortion_age_plot + age_bronx)/(age_brooklyn + age_manhattan) / (age_queens + age_si)

ggsave("results/abortion_age.pdf", abortion_age_plot, width = 10, height = 5)

ggsave("results/abortion_age_wtotal.pdf", abortion_age_wtotal_plot, width = 10, height = 5)

ggsave("results/matrix_age.pdf", matrix_age, width = 15, height = 15)


```