---
title: "Master"
author: "Maisie Sun"
date: "2022-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(janitor)
library(ggridges)
library(patchwork)
library(readxl)
library("writexl")
library(rvest)
library(httr)
library(dplyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Import age

```{r data_import_age, echo = FALSE}
url = "https://www.health.ny.gov/statistics/vital_statistics/2019/table22.htm"

induced_abortion = 
  read_html(url) %>%
  html_table(header = FALSE) %>%
  first() %>%
  janitor::clean_names()

clean_age = 
  induced_abortion %>%
  select(1:8) %>%
  purrr::set_names(c("borough", "total", "age_less_20", "age_20_24", "age_25_29", "age_30_34", "age_35_39", "age_plus_40")) %>%
  slice(7:11,14:70) %>%
  mutate(
    borough = str_replace(borough, "Kings", "Brooklyn"),
    borough = ifelse(as.character(borough) == "New York", "Manhattan", as.character(borough)),
    borough = str_replace(borough, "Richmond", "Staten Island"),
    total = str_replace(total, ",", ""),
    age_less_20 = str_replace(age_less_20, ",", ""),
    age_20_24 = str_replace(age_20_24, ",", ""),
    age_25_29 = str_replace(age_25_29, ",", ""),
    age_30_34 = str_replace(age_30_34, ",", ""),
    age_35_39 = str_replace(age_35_39, ",", ""),
    age_plus_40 = str_replace(age_plus_40, ",", "")
    ) %>%
  mutate_at(c("total", "age_less_20", "age_20_24", "age_25_29", "age_30_34", "age_35_39", "age_plus_40"), as.numeric) 

```

## Import Race

```{r}
url = "https://www.health.ny.gov/statistics/vital_statistics/2019/table23.htm"

induced_abortion_race = 
  read_html(url) %>%
  html_table(header = FALSE) %>%
  first() %>%
  janitor::clean_names()

clean_race = 
  induced_abortion_race %>%
  select(1,3,5,7,9,11,13,15,17) %>% 
  purrr::set_names(c("borough", "total", "nh_total", "nh_white_only_Ratio", "nh_black_only_ratio", "nh_other_ratio", "h_total", "n_white_only_ratio", "n_black_only_ratio")) %>% 
  slice(7:11,14:70) %>%
  mutate(
    borough = str_replace(borough, "Kings", "Brooklyn"),
    borough = ifelse(as.character(borough) == "New York", "Manhattan", as.character(borough)),
    borough = str_replace(borough, "Richmond", "Staten Island"),
    total = str_replace(total, ",", ""),
    nh_total = str_replace(nh_total, ",", ""),
    nh_white_only_Ratio = str_replace(nh_white_only_Ratio, ",", ""),
    nh_black_only_ratio = str_replace(nh_black_only_ratio, ",", ""),
    nh_other_ratio = str_replace(nh_other_ratio, ",", ""),
    h_total = str_replace(h_total, ",", ""),
    n_white_only_ratio = str_replace(n_white_only_ratio, ",", ""),
    n_black_only_ratio = str_replace(n_black_only_ratio, ",", "")
    ) %>%
  mutate_at(c(2:9), as.numeric) %>%
    janitor::clean_names()

```

## Import Finance

```{r}
url = "https://www.health.ny.gov/statistics/vital_statistics/2019/table24.htm"
url1 = "https://www.health.ny.gov/statistics/vital_statistics/2019/table13.htm"

induced_abortion_finance = 
  read_html(url) %>%
  html_table(header = FALSE) %>%
  first() %>%
  janitor::clean_names()

live_birth_finance = 
  read_html(url1) %>%
  html_table(header = FALSE) %>%
  first() %>%
  janitor::clean_names()
```

Clean live birth finance

```{r}
clean_lb_finance = 
  live_birth_finance %>% 
  select(-c(4,6:8)) %>%
  purrr::set_names(c("borough", "total", "medicaid", "self_pay", "other_insurance", "not_stated")) %>%
  slice(7:11,14:70) %>%
  mutate(
    borough = str_replace(borough, "Kings", "Brooklyn"),
    borough = ifelse(as.character(borough) == "New York", "Manhattan", as.character(borough)),
    borough = str_replace(borough, "Richmond", "Staten Island"),
    total = str_replace(total, ",", ""),
    medicaid = str_replace(medicaid, ",", ""),
    other_insurance = str_replace(other_insurance, ",", ""),
    self_pay = str_replace(self_pay, ",", ""),
    not_stated = str_replace(not_stated, ",", "")
    ) %>%
  transform(borough = gsub(pattern="Essex|Hamilton", replacement="Essex/Hamilton", borough)) %>% 
  mutate_at(c(2:6), as.numeric) %>% 
  group_by(borough) %>%
  summarise(
    total = sum(total),
    medicaid = sum(medicaid),
    other_insurance = sum(other_insurance),
    self_pay = sum(self_pay),
    not_stated = sum(not_stated)
  )

```

Clean abortion finance

```{r}
clean_ia_finance =
induced_abortion_finance %>%
  select(c(1:3,5,6,8)) %>%
  purrr::set_names(c("borough", "total", "Medicaid", "Other_Insurance", "Self_Pay", "Not_Stated")) %>%
  slice(7:11,14:70) %>%
  mutate(
    borough = str_replace(borough, "Kings", "Brooklyn"),
    borough = ifelse(as.character(borough) == "New York", "Manhattan", as.character(borough)),
    borough = str_replace(borough, "Richmond", "Staten Island"),
    total = str_replace(total, ",", ""),
    Medicaid = str_replace(Medicaid, ",", ""),
    Other_Insurance = str_replace(Other_Insurance, ",", ""),
    Self_Pay = str_replace(Self_Pay, ",", ""),
    Not_Stated = str_replace(Not_Stated, ",", "")
    ) %>%
  janitor::clean_names() %>%
  mutate_at(c(2:6), as.numeric)
```

merge finance

```{r}
merged_data=
  full_join(clean_lb_finance,clean_ia_finance, by="borough") %>%
  janitor::clean_names() %>%
  mutate(
    medicaid = (medicaid_y / medicaid_x)*1000,
    self_pay = (self_pay_y / self_pay_x)*1000,
    other_insurance = (other_insurance_y / other_insurance_x)*1000,
    not_stated = (not_stated_y / not_stated_x)*1000,
    total = (total_y / total_x)*1000) %>% 
select(borough, medicaid, self_pay, other_insurance, not_stated, total)

```

merge all dataset

```{r}
merge_age_race = 
  full_join(clean_age, clean_race, by = "borough") %>% 
  select(-total.y)

merge_final = 
  full_join(merge_age_race, merged_data, by = "borough") %>%
  select(-total.x) %>%
  filter(!row_number() %in% c(25, 63, 64)) %>%
  mutate(
    other_insurance = na_if(other_insurance, "Inf"),
    not_stated = na_if(not_stated, "Inf")
  )

write_csv(merge_final, file = "data/master.csv")

```
